/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class BoxListData extends AbstractBoxListData implements IBoxListData {
	
	public BoxListData(
		@JsonProperty("boxList") java.util.List<com.anfelisa.box.models.IBoxViewModel> boxList, 
		@JsonProperty("userId") String userId, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			boxList,
			userId,
			uuid
		);
	}

	public BoxListData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.box.models.IBoxListModel generateTestData() {
		java.util.Random random = new java.util.Random();
		int n;
		com.anfelisa.box.models.IBoxListModel testData = new com.anfelisa.box.models.BoxListModel();
		java.util.List<com.anfelisa.box.models.IBoxViewModel> boxListList = new java.util.ArrayList<com.anfelisa.box.models.IBoxViewModel>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			boxListList.add(com.anfelisa.box.data.BoxViewData.generateTestData());
		}
		testData.setBoxList(boxListList);
		testData.setUserId(randomString(random));
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



