/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




package com.anfelisa.box.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class BoxSettingsWrapperData extends AbstractBoxSettingsWrapperData implements IBoxSettingsWrapperData {
	
	public BoxSettingsWrapperData(
		@JsonProperty("userId") String userId, 
		@JsonProperty("boxId") String boxId, 
		@JsonProperty("boxSettings") com.anfelisa.box.models.IBoxSettingsModel boxSettings, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			userId,
			boxId,
			boxSettings,
			uuid
		);
	}

	public BoxSettingsWrapperData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.box.models.IBoxSettingsWrapperModel generateTestData() {
		java.util.Random random = new java.util.Random();
		com.anfelisa.box.models.IBoxSettingsWrapperModel testData = new com.anfelisa.box.models.BoxSettingsWrapperModel();
		testData.setUserId(randomString(random));
		testData.setBoxId(randomString(random));
		testData.setBoxSettings(com.anfelisa.box.data.BoxSettingsData.generateTestData());
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



