/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.box.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class DeleteBoxData extends AbstractDeleteBoxData implements IDeleteBoxData {
	
	public DeleteBoxData(
		@JsonProperty("userId") String userId, 
		@JsonProperty("boxId") String boxId, 
		@JsonProperty("rootCategoryId") String rootCategoryId, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			userId,
			boxId,
			rootCategoryId,
			uuid
		);
	}

	public DeleteBoxData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.box.models.IDeleteBoxModel generateTestData() {
		java.util.Random random = new java.util.Random();
		com.anfelisa.box.models.IDeleteBoxModel testData = new com.anfelisa.box.models.DeleteBoxModel();
		testData.setUserId(randomString(random));
		testData.setBoxId(randomString(random));
		testData.setRootCategoryId(randomString(random));
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



