/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.box.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class InitMyBoxesDataData extends AbstractInitMyBoxesDataData implements IInitMyBoxesDataData {
	
	public InitMyBoxesDataData(
		@JsonProperty("userId") String userId, 
		@JsonProperty("todayAtMidnightInUTC") java.time.LocalDateTime todayAtMidnightInUTC, 
		@JsonProperty("postponeCards") java.util.List<com.anfelisa.box.models.IPostponeCardsModel> postponeCards, 
		@JsonProperty("outdatedReinforceCardsIds") java.util.List<String> outdatedReinforceCardsIds, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			userId,
			todayAtMidnightInUTC,
			postponeCards,
			outdatedReinforceCardsIds,
			uuid
		);
	}

	public InitMyBoxesDataData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.box.models.IInitMyBoxesDataModel generateTestData() {
		java.util.Random random = new java.util.Random();
		int n;
		com.anfelisa.box.models.IInitMyBoxesDataModel testData = new com.anfelisa.box.models.InitMyBoxesDataModel();
		testData.setUserId(randomString(random));
		testData.setTodayAtMidnightInUTC(random.nextBoolean() ? java.time.LocalDateTime.now().plusMinutes(random.nextInt(60)) : java.time.LocalDateTime.now().minusMinutes(random.nextInt(60)) );
		java.util.List<com.anfelisa.box.models.IPostponeCardsModel> postponeCardsList = new java.util.ArrayList<com.anfelisa.box.models.IPostponeCardsModel>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			postponeCardsList.add(com.anfelisa.box.data.PostponeCardsData.generateTestData());
		}
		testData.setPostponeCards(postponeCardsList);
		java.util.List<String> outdatedReinforceCardsIdsList = new java.util.ArrayList<String>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			outdatedReinforceCardsIdsList.add(randomString(random));
		}
		testData.setOutdatedReinforceCardsIds(outdatedReinforceCardsIdsList);
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



