/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class NextCardData extends AbstractNextCardData implements INextCardData {
	
	public NextCardData(
		@JsonProperty("userId") String userId, 
		@JsonProperty("boxId") String boxId, 
		@JsonProperty("nextCard") com.anfelisa.box.models.INextCardViewModel nextCard, 
		@JsonProperty("reverse") Boolean reverse, 
		@JsonProperty("openTodaysCards") Integer openTodaysCards, 
		@JsonProperty("allTodaysCards") Integer allTodaysCards, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			userId,
			boxId,
			nextCard,
			reverse,
			openTodaysCards,
			allTodaysCards,
			uuid
		);
	}

	public NextCardData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.box.models.INextCardModel generateTestData() {
		java.util.Random random = new java.util.Random();
		com.anfelisa.box.models.INextCardModel testData = new com.anfelisa.box.models.NextCardModel();
		testData.setUserId(randomString(random));
		testData.setBoxId(randomString(random));
		testData.setNextCard(com.anfelisa.box.data.NextCardViewData.generateTestData());
		testData.setReverse(random.nextBoolean());
		testData.setOpenTodaysCards(random.nextInt(50));
		testData.setAllTodaysCards(random.nextInt(50));
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



