/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.box.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ReinforceCardData extends AbstractReinforceCardData implements IReinforceCardData {
	
	public ReinforceCardData(
		@JsonProperty("reinforceCardId") String reinforceCardId, 
		@JsonProperty("scheduledCardId") String scheduledCardId, 
		@JsonProperty("boxId") String boxId, 
		@JsonProperty("changeDate") java.time.LocalDateTime changeDate, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			reinforceCardId,
			scheduledCardId,
			boxId,
			changeDate,
			uuid
		);
	}

	public ReinforceCardData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.box.models.IReinforceCardModel generateTestData() {
		java.util.Random random = new java.util.Random();
		com.anfelisa.box.models.IReinforceCardModel testData = new com.anfelisa.box.models.ReinforceCardModel();
		testData.setReinforceCardId(randomString(random));
		testData.setScheduledCardId(randomString(random));
		testData.setBoxId(randomString(random));
		testData.setChangeDate(random.nextBoolean() ? java.time.LocalDateTime.now().plusMinutes(random.nextInt(60)) : java.time.LocalDateTime.now().minusMinutes(random.nextInt(60)) );
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



