/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.box.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class SortCardsOutData extends AbstractSortCardsOutData implements ISortCardsOutData {
	
	public SortCardsOutData(
		@JsonProperty("sortedOutScheduledCardIds") java.util.List<String> sortedOutScheduledCardIds, 
		@JsonProperty("sortedOutReinforceCardIds") java.util.List<String> sortedOutReinforceCardIds, 
		@JsonProperty("cardIds") java.util.List<String> cardIds, 
		@JsonProperty("userId") String userId, 
		@JsonProperty("boxId") String boxId, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			sortedOutScheduledCardIds,
			sortedOutReinforceCardIds,
			cardIds,
			userId,
			boxId,
			uuid
		);
	}

	public SortCardsOutData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.box.models.ISortCardsOutModel generateTestData() {
		java.util.Random random = new java.util.Random();
		int n;
		com.anfelisa.box.models.ISortCardsOutModel testData = new com.anfelisa.box.models.SortCardsOutModel();
		java.util.List<String> sortedOutScheduledCardIdsList = new java.util.ArrayList<String>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			sortedOutScheduledCardIdsList.add(randomString(random));
		}
		testData.setSortedOutScheduledCardIds(sortedOutScheduledCardIdsList);
		java.util.List<String> sortedOutReinforceCardIdsList = new java.util.ArrayList<String>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			sortedOutReinforceCardIdsList.add(randomString(random));
		}
		testData.setSortedOutReinforceCardIds(sortedOutReinforceCardIdsList);
		java.util.List<String> cardIdsList = new java.util.ArrayList<String>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			cardIdsList.add(randomString(random));
		}
		testData.setCardIds(cardIdsList);
		testData.setUserId(randomString(random));
		testData.setBoxId(randomString(random));
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



