/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.box.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class TodaysCardsStatusData extends AbstractTodaysCardsStatusData implements ITodaysCardsStatusData {
	
	public TodaysCardsStatusData(
		@JsonProperty("openTodaysCards") Integer openTodaysCards, 
		@JsonProperty("allTodaysCards") Integer allTodaysCards, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			openTodaysCards,
			allTodaysCards,
			uuid
		);
	}

	public TodaysCardsStatusData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.box.models.ITodaysCardsStatusModel generateTestData() {
		java.util.Random random = new java.util.Random();
		com.anfelisa.box.models.ITodaysCardsStatusModel testData = new com.anfelisa.box.models.TodaysCardsStatusModel();
		testData.setOpenTodaysCards(random.nextInt(50));
		testData.setAllTodaysCards(random.nextInt(50));
		return testData;
	}
	
}



/******* S.D.G. *******/



