/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.movecategory.scenarios;

import com.anfelisa.category.data.MoveCategoryResponse;

@SuppressWarnings("unused")
public class MoveCategoryMovedCategoryIsNullScenario extends AbstractMoveCategoryMovedCategoryIsNullScenario {

	

}




/******* S.D.G. *******/



