/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.movecategory.scenarios;

@SuppressWarnings("unused")
public class MoveCategoryNoAccessToTargetCategoryScenario extends AbstractMoveCategoryNoAccessToTargetCategoryScenario {

	

}




/******* S.D.G. *******/



