/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.user.commands;

import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.auth.Roles;
import com.anfelisa.box.models.BoxModel;
import com.anfelisa.box.utils.Deletable;
import com.anfelisa.user.models.DeleteUserModel;
import com.anfelisa.user.models.UserModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.Data;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class DeleteUserCommand extends AbstractDeleteUserCommand {

	static final Logger LOG = LoggerFactory.getLogger(DeleteUserCommand.class);

	public DeleteUserCommand(IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected Data<DeleteUserModel> executeCommand(Data<DeleteUserModel> data, PersistenceHandle readonlyHandle) {
		if (!Roles.ADMIN.equals(data.getModel().getRole())
				&& !data.getModel().getUsername().equals(data.getModel().getUsernameToBeDeleted())) {
			throwSecurityException();
		}
		UserModel userToBeDeleted = daoProvider.getUserDao().selectByUsername(readonlyHandle,
				data.getModel().getUsernameToBeDeleted());
		if (userToBeDeleted == null) {
			throwIllegalArgumentException("userDoesNotExist");
		}
		if (Roles.ADMIN.equals(userToBeDeleted.getRole())) {
			if (daoProvider.getUserDao().selectAdminCount(readonlyHandle) == 1) {
				throwIllegalArgumentException("lastAdminMustNotBeDeleted");
			}
		}
		List<BoxModel> boxesOfUser = daoProvider.getBoxDao().selectAllOfUser(readonlyHandle, userToBeDeleted.getUserId());
		List<String> rootCategoryIds = new ArrayList<>();
		for (BoxModel box : boxesOfUser) {
			if (!Deletable.isBoxDeletable(daoProvider, readonlyHandle, box.getCategoryId(), box.getReverse(), data.getModel().getUserId())) {
				throwIllegalArgumentException("cannot delete user with shared boxes");
			} 
			if (Deletable.onDeleteBoxDeleteCategory(daoProvider, readonlyHandle, box)) {
				rootCategoryIds.add(box.getCategoryId());
			}
		}
		data.getModel().setRootCategoryIds(rootCategoryIds);
		data.getModel().setUserId(userToBeDeleted.getUserId());
		this.addOkOutcome(data);
		return data;
	}

}




/******* S.D.G. *******/



