/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.user.commands;

import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.auth.Roles;
import com.anfelisa.box.models.IBoxModel;
import com.anfelisa.user.data.IDeleteUserData;
import com.anfelisa.user.models.IUserModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class DeleteUserCommand extends AbstractDeleteUserCommand {

	static final Logger LOG = LoggerFactory.getLogger(DeleteUserCommand.class);

	public DeleteUserCommand(IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected IDeleteUserData executeCommand(IDeleteUserData data, PersistenceHandle readonlyHandle) {
		if (!Roles.ADMIN.equals(data.getRole())
				&& !data.getUsername().equals(data.getUsernameToBeDeleted())) {
			throwSecurityException();
		}
		IUserModel userToBeDeleted = daoProvider.getUserDao().selectByUsername(readonlyHandle,
				data.getUsernameToBeDeleted());
		if (userToBeDeleted == null) {
			throwIllegalArgumentException("userDoesNotExist");
		}
		if (Roles.ADMIN.equals(userToBeDeleted.getRole())) {
			if (daoProvider.getUserDao().selectAdminCount(readonlyHandle) == 1) {
				throwIllegalArgumentException("lastAdminMustNotBeDeleted");
			}
		}
		List<IBoxModel> boxesOfUser = daoProvider.getBoxDao().selectAllOfUser(readonlyHandle, userToBeDeleted.getUserId());
		List<String> boxIds = new ArrayList<>();
		List<String> rootCategoryIds = new ArrayList<>();
		for (IBoxModel box : boxesOfUser) {
			boxIds.add(box.getBoxId());
			rootCategoryIds.add(box.getCategoryId());
		}
		data.setBoxIds(boxIds);
		data.setRootCategoryIds(rootCategoryIds);
		data.setUserId(userToBeDeleted.getUserId());
		this.addOkOutcome(data);
		return data;
	}

}




/******* S.D.G. *******/



