/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/

package com.anfelisa.user.commands;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.auth.Roles;
import com.anfelisa.user.data.IUserRegistrationData;
import com.anfelisa.user.models.IUserModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class RegisterUserCommand extends AbstractRegisterUserCommand {

	static final Logger LOG = LoggerFactory.getLogger(RegisterUserCommand.class);

	public RegisterUserCommand(IDaoProvider daoProvider, ViewProvider viewProvider,
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected IUserRegistrationData executeCommand(IUserRegistrationData data, PersistenceHandle readonlyHandle) {
		IUserModel user = daoProvider.getUserDao().selectByUsername(readonlyHandle, data.getUsername());
		if (user != null) {
			throwIllegalArgumentException("usernameAlreadyTaken");
		}
		if ("Admin".equals(data.getUsername())) {
			data.setRole(Roles.ADMIN);
		} else {
			data.setRole(Roles.STUDENT);
		}
		data.setUserId(data.getUuid());
		data.setEmailConfirmed(false);
		this.addOkOutcome(data);
		return data;
	}

}

/******* S.D.G. *******/
