/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/

package com.anfelisa.user.commands;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.auth.Roles;
import com.anfelisa.user.models.UserModel;
import com.anfelisa.user.models.UserRegistrationModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.Data;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class RegisterUserCommand extends AbstractRegisterUserCommand {

	static final Logger LOG = LoggerFactory.getLogger(RegisterUserCommand.class);

	public RegisterUserCommand(IDaoProvider daoProvider, ViewProvider viewProvider,
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected Data<UserRegistrationModel> executeCommand(Data<UserRegistrationModel> data, PersistenceHandle readonlyHandle) {
		UserModel user = daoProvider.getUserDao().selectByUsername(readonlyHandle, data.getModel().getUsername());
		if (user != null) {
			throwIllegalArgumentException("usernameAlreadyTaken");
		}
		if ("Admin".equals(data.getModel().getUsername())) {
			data.getModel().setRole(Roles.ADMIN);
		} else {
			data.getModel().setRole(Roles.STUDENT);
		}
		data.getModel().setUserId(data.getUuid());
		data.getModel().setEmailConfirmed(false);
		this.addOkOutcome(data);
		return data;
	}

}

/******* S.D.G. *******/
