/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/

package com.anfelisa.user.commands;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.user.data.IResetPasswordWithNewPasswordData;
import com.anfelisa.user.models.IResetPasswordModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class ResetPasswordCommand extends AbstractResetPasswordCommand {

	static final Logger LOG = LoggerFactory.getLogger(ResetPasswordCommand.class);

	public ResetPasswordCommand(IDaoProvider daoProvider, ViewProvider viewProvider,
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected IResetPasswordWithNewPasswordData executeCommand(IResetPasswordWithNewPasswordData data,
			PersistenceHandle readonlyHandle) {
		IResetPasswordModel model = daoProvider.getResetPasswordDao().selectByToken(readonlyHandle,
				data.getToken());
		if (model == null) {
			throwIllegalArgumentException("tokenDoesNotExist");
		}
		data.setUserId(model.getUserId());
		this.addOkOutcome(data);
		return data;
	}

}

/******* S.D.G. *******/
