/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




package com.anfelisa.box.initmyboxes.scenarios;

import com.anfelisa.box.data.InitMyBoxesForDayResponse;

@SuppressWarnings("unused")
public class InitMyBoxesForDayArchivedScenario extends AbstractInitMyBoxesForDayArchivedScenario {

	

}




/******* S.D.G. *******/



