/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.initmyboxes.scenarios;


public class InitMyBoxesForDayArchivedScenario extends AbstractInitMyBoxesForDayArchivedScenario {

	

}




/******* S.D.G. *******/



