/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




package com.anfelisa.box.archivebox.scenarios;

import com.anfelisa.box.data.ArchiveBoxResponse;

@SuppressWarnings("unused")
public class ArchiveBoxNoAccessScenario extends AbstractArchiveBoxNoAccessScenario {

	

}




/******* S.D.G. *******/



