/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.archivebox.scenarios;


public class ArchiveBoxNoAccessScenario extends AbstractArchiveBoxNoAccessScenario {

	

}




/******* S.D.G. *******/



