/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.deletecategory.scenarios;

@SuppressWarnings("unused")
public class DeleteCategoryNoEditingAccessScenario extends AbstractDeleteCategoryNoEditingAccessScenario {

	

}




/******* S.D.G. *******/



