/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.user.actions;

import java.util.UUID;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.user.data.IForgotPasswordData;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;
import de.acegen.ViewProvider;

public class ForgotPasswordAction extends AbstractForgotPasswordAction {

	static final Logger LOG = LoggerFactory.getLogger(ForgotPasswordAction.class);

	public ForgotPasswordAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration, IDaoProvider daoProvider, 
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}
	
	public IForgotPasswordData initActionData(IForgotPasswordData data) {
		data.setToken(UUID.randomUUID().toString());
		return data;
	}

}



/******* S.D.G. *******/



