/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




package com.anfelisa.user.actions;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.user.models.UserInfoModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.Data;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class GetUserInfoAction extends AbstractGetUserInfoAction {

	static final Logger LOG = LoggerFactory.getLogger(GetUserInfoAction.class);

	public GetUserInfoAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration, IDaoProvider daoProvider, 
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}


	@Override
	protected Data<UserInfoModel> loadDataForGetRequest(Data<UserInfoModel> data, PersistenceHandle readonlyHandle) {
		return data;
	}
	

}



/******* S.D.G. *******/



