/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




package com.anfelisa.user.actions;

import de.acegen.CustomAppConfiguration;
import de.acegen.ViewProvider;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;
import de.acegen.PersistenceHandle;
import com.anfelisa.user.data.IUserInfoData;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class GetUserInfoAction extends AbstractGetUserInfoAction {

	static final Logger LOG = LoggerFactory.getLogger(GetUserInfoAction.class);

	public GetUserInfoAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration, IDaoProvider daoProvider, 
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}


	@Override
	protected IUserInfoData loadDataForGetRequest(IUserInfoData data, PersistenceHandle readonlyHandle) {
		return data;
	}
	

}



/******* S.D.G. *******/



