/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/

package com.anfelisa.user.actions;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.box.models.BoxModel;
import com.anfelisa.box.utils.Deletable;
import com.anfelisa.user.models.ProfileUserModel;
import com.anfelisa.user.models.UserModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.Data;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class GetUserProfileAction extends AbstractGetUserProfileAction {

	static final Logger LOG = LoggerFactory.getLogger(GetUserProfileAction.class);

	public GetUserProfileAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration,
			IDaoProvider daoProvider,
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}

	@Override
	protected Data<ProfileUserModel> loadDataForGetRequest(Data<ProfileUserModel> data, PersistenceHandle readonlyHandle) {
		UserModel user = daoProvider.getUserDao().selectByUsername(readonlyHandle, data.getModel().getUsername());
		data.getModel().setEmail(user.getEmail());
		data.getModel().setEmailConfirmed(user.getEmailConfirmed());
		List<BoxModel> boxesOfUser = daoProvider.getBoxDao().selectAllOfUser(readonlyHandle, data.getModel().getUserId());
		data.getModel().setDeletable(true);
		for (BoxModel box : boxesOfUser) {
			if (!Deletable.isBoxDeletable(daoProvider, readonlyHandle, box.getCategoryId(), box.getReverse(), data.getModel().getUserId())) {
				data.getModel().setDeletable(false);
			}
		}
		return data;
	}


}

/******* S.D.G. *******/
