/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/

package com.anfelisa.user.actions;

import de.acegen.CustomAppConfiguration;
import de.acegen.ViewProvider;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;
import de.acegen.PersistenceHandle;
import com.anfelisa.user.data.IUsernameAvailableData;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class UsernameAvailableAction extends AbstractUsernameAvailableAction {

	static final Logger LOG = LoggerFactory.getLogger(UsernameAvailableAction.class);

	public UsernameAvailableAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration,
			IDaoProvider daoProvider,
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}

	@Override
	protected IUsernameAvailableData loadDataForGetRequest(IUsernameAvailableData data,
			PersistenceHandle readonlyHandle) {
		if (daoProvider.getUserDao().selectByUsername(readonlyHandle,
				data.getUsername()) == null) {
			data.setAvailable(true);
		} else {
			data.setAvailable(false);
		}
		return data;
	}

}

/******* S.D.G. *******/
