/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.card.updatecard.scenarios;

import com.anfelisa.card.data.UpdateCardResponse;

@SuppressWarnings("unused")
public class UpdateCardNoEditingAccessToCardScenario extends AbstractUpdateCardNoEditingAccessToCardScenario {

	

}




/******* S.D.G. *******/



