/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.card.updatecard.scenarios;

@SuppressWarnings("unused")
public class UpdateCardNoAccessToCardScenario extends AbstractUpdateCardNoAccessToCardScenario {

	

}




/******* S.D.G. *******/



