/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




package com.anfelisa.box.getboxstatistics.scenarios;

import com.anfelisa.box.data.GetBoxStatisticsResponse;

@SuppressWarnings("unused")
public class GetBoxesArchivedScenario extends AbstractGetBoxesArchivedScenario {

	

}




/******* S.D.G. *******/



