/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.box.scorereinforcecard.scenarios;

import com.anfelisa.box.data.ScoreReinforceCardResponse;

@SuppressWarnings("unused")
public class ScoreReinforceCardKeepScenario extends AbstractScoreReinforceCardKeepScenario {

	

}




/******* S.D.G. *******/



