/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.box.scorereinforcecard.scenarios;

@SuppressWarnings("unused")
public class ScoreReinforceCardRemoveScenario extends AbstractScoreReinforceCardRemoveScenario {

	

}




/******* S.D.G. *******/



