/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.card.commands;

import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.card.data.IChangeCardOrderListData;
import com.anfelisa.card.models.ICardModel;
import com.anfelisa.category.models.IUserAccessToCategoryModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class ChangeOrderCommand extends AbstractChangeOrderCommand {

	static final Logger LOG = LoggerFactory.getLogger(ChangeOrderCommand.class);

	public ChangeOrderCommand(IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected IChangeCardOrderListData executeCommand(IChangeCardOrderListData data, PersistenceHandle readonlyHandle) {
		ICardModel targetCard = daoProvider.getCardDao().selectByCardId(readonlyHandle, data.getCardId());
		if (targetCard == null) {
			throwIllegalArgumentException("cardDoesNotExist");
		}
		IUserAccessToCategoryModel accessToRootCategory = this.daoProvider.getUserAccessToCategoryDao()
				.hasUserAccessTo(readonlyHandle, targetCard.getRootCategoryId(), data.getUserId());
		if (accessToRootCategory == null || !accessToRootCategory.getEditable()) {
			throwSecurityException();
		}
		for (String cardId : data.getCardIdList()) {
			ICardModel card = daoProvider.getCardDao().selectByCardId(readonlyHandle, cardId);
			if (card == null) {
				throwIllegalArgumentException("cardDoesNotExist");
			}
			accessToRootCategory = this.daoProvider.getUserAccessToCategoryDao()
					.hasUserAccessTo(readonlyHandle, card.getRootCategoryId(), data.getUserId());
			if (accessToRootCategory == null || !accessToRootCategory.getEditable()) {
				throwSecurityException();
			}
		}
		List<ICardModel> cards = daoProvider.getCardDao().selectAll(readonlyHandle, targetCard.getCategoryId());
		int index = 1;
		for (ICardModel card : cards) {
			if (card.getCardIndex() < targetCard.getCardIndex()) {
				if (!data.getCardIdList().contains(card.getCardId())) {
					card.setCardIndex(index);
					index++;
				}
			} else {
				break;
			}
		}
		List<ICardModel> movedCards = orderedMovedCards(data, cards);
		for (ICardModel card : movedCards) {
			card.setCardIndex(index);
			index++;
		}
		for (ICardModel card : cards) {
			if (card.getCardIndex() >= targetCard.getCardIndex()) {
				if (!data.getCardIdList().contains(card.getCardId())) {
					card.setCardIndex(index);
					index++;
				}
			}
		}
		data.setUpdatedIndices(cards);
		this.addOkOutcome(data);
		return data;
	}

	private List<ICardModel> orderedMovedCards(IChangeCardOrderListData data, List<ICardModel> cards) {
		List<ICardModel> movedCards = new ArrayList<ICardModel>();
		for (ICardModel card : cards) {
			if (data.getCardIdList().contains(card.getCardId())) {
				movedCards.add(card);
			}
		}
		return movedCards;
	}

}




/******* S.D.G. *******/



