/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.card.commands;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.card.models.CardCreationModel;
import com.anfelisa.category.models.CategoryModel;
import com.anfelisa.category.models.UserAccessToCategoryModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.Data;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class CreateCardCommand extends AbstractCreateCardCommand {

	static final Logger LOG = LoggerFactory.getLogger(CreateCardCommand.class);

	public CreateCardCommand(IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected Data<CardCreationModel> executeCommand(Data<CardCreationModel> data, PersistenceHandle readonlyHandle) {
		CategoryModel category = this.daoProvider.getCategoryDao().selectByCategoryId(readonlyHandle,
				data.getModel().getCategoryId());
		if (category == null) {
			throwIllegalArgumentException("categoryDoesNotExist");
		}
		UserAccessToCategoryModel access = this.daoProvider.getUserAccessToCategoryDao()
				.selectByCategoryIdAndUserId(readonlyHandle, category.getRootCategoryId(), data.getModel().getUserId());
		if (access == null || !access.getEditable()) {
			throwSecurityException();
		}
		data.getModel().setRootCategoryId(category.getRootCategoryId());
		data.getModel().setCardId(data.getUuid());
		Integer max = this.daoProvider.getCardDao().selectMaxIndexInCategory(readonlyHandle,
				data.getModel().getCategoryId());
		if (max == null) {
			max = 0;
		}
		data.getModel().setCardIndex(max + 1);
		data.getModel().setCardAuthor(data.getModel().getUsername());
		this.addOkOutcome(data);
		return data;
	}

}




/******* S.D.G. *******/



