/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.card.commands;

import java.util.ArrayList;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.card.models.CardDeleteItemModel;
import com.anfelisa.card.models.CardDeleteModel;
import com.anfelisa.card.models.CardModel;
import com.anfelisa.category.models.UserAccessToCategoryModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.Data;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class DeleteCardCommand extends AbstractDeleteCardCommand {

	static final Logger LOG = LoggerFactory.getLogger(DeleteCardCommand.class);

	public DeleteCardCommand(IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected Data<CardDeleteModel> executeCommand(Data<CardDeleteModel> data, PersistenceHandle readonlyHandle) {
		data.getModel().setCardDeleteItems(new ArrayList<>());
		for (String cardId : data.getModel().getCardIds().split(",")) {
			CardModel card = daoProvider.getCardDao().selectByCardId(readonlyHandle, cardId.trim());
			if (card == null) {
				throwIllegalArgumentException("cardDoesNotExist");
			}
			UserAccessToCategoryModel access = this.daoProvider.getUserAccessToCategoryDao()
					.selectByCategoryIdAndUserId(readonlyHandle, card.getRootCategoryId(), data.getModel().getUserId());
			if (access == null || !access.getEditable()) {
				throwSecurityException();
			}
			CardDeleteItemModel cardDeleteItem = new CardDeleteItemModel();
			cardDeleteItem.setCardId(cardId);
			cardDeleteItem.setCardIndex(card.getCardIndex());
			cardDeleteItem.setCategoryId(card.getCategoryId());
			data.getModel().getCardDeleteItems().add(cardDeleteItem);
		}
		this.addOkOutcome(data);
		return data;
	}

}




/******* S.D.G. *******/



