/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.card.commands;

import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.card.models.CardModel;
import com.anfelisa.card.models.MoveCardsModel;
import com.anfelisa.category.models.UserAccessToCategoryModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.Data;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class MoveCardsCommand extends AbstractMoveCardsCommand {

	static final Logger LOG = LoggerFactory.getLogger(MoveCardsCommand.class);

	public MoveCardsCommand(IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected Data<MoveCardsModel> executeCommand(Data<MoveCardsModel> data, PersistenceHandle readonlyHandle) {
		UserAccessToCategoryModel accessToCategory = this.daoProvider.getUserAccessToCategoryDao()
				.hasUserAccessTo(readonlyHandle, data.getModel().getCategoryId(), data.getModel().getUserId());
		if (accessToCategory == null || !accessToCategory.getEditable()) {
			throwSecurityException();
		}
		Integer cardIndex = this.daoProvider.getCardDao().selectMaxIndexInCategory(readonlyHandle,
				data.getModel().getCategoryId());
		if (cardIndex == null) {
			cardIndex = 1;
		} else {
			cardIndex++;
		}
		List<CardModel> movedCards = new ArrayList<>();
		String sourceCategoryId = "";
		for (String cardId : data.getModel().getCardIdList()) {
			CardModel card = daoProvider.getCardDao().selectByCardId(readonlyHandle, cardId);
			if (card == null) {
				throwIllegalArgumentException("cardDoesNotExist");
			}
			UserAccessToCategoryModel accessToRootCategory = this.daoProvider.getUserAccessToCategoryDao()
					.hasUserAccessTo(readonlyHandle, card.getRootCategoryId(), data.getModel().getUserId());
			if (accessToRootCategory == null || !accessToRootCategory.getEditable()) {
				throwSecurityException();
			}
			sourceCategoryId = card.getCategoryId();
			card.setCardIndex(cardIndex);
			card.setCategoryId(data.getModel().getCategoryId());
			movedCards.add(card);
			cardIndex++;
		}
		data.getModel().setMovedCards(movedCards);

		List<CardModel> updatedIndices = new ArrayList<>();
		cardIndex = 1;
		List<CardModel> allCardsInSourceCategory = this.daoProvider.getCardDao().selectAll(readonlyHandle,
				sourceCategoryId);
		for (CardModel card : allCardsInSourceCategory) {
			if (!data.getModel().getCardIdList().contains(card.getCardId())) {
				card.setCardIndex(cardIndex);
				updatedIndices.add(card);
				cardIndex++;
			}
		}
		data.getModel().setUpdatedIndices(updatedIndices);

		this.addOkOutcome(data);
		return data;
	}

}




/******* S.D.G. *******/



