/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.card.commands;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.card.models.CardModel;
import com.anfelisa.card.models.CardUpdateModel;
import com.anfelisa.category.models.UserAccessToCategoryModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.Data;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class UpdateCardCommand extends AbstractUpdateCardCommand {

	static final Logger LOG = LoggerFactory.getLogger(UpdateCardCommand.class);

	public UpdateCardCommand(IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected Data<CardUpdateModel> executeCommand(Data<CardUpdateModel> data, PersistenceHandle readonlyHandle) {
		CardModel card = daoProvider.getCardDao().selectByCardId(readonlyHandle,  data.getModel().getCardId());
		if (card == null) {
			throwIllegalArgumentException("cardDoesNotExist");
		}
		UserAccessToCategoryModel access = this.daoProvider.getUserAccessToCategoryDao().selectByCategoryIdAndUserId(readonlyHandle,  card.getRootCategoryId(), data.getModel().getUserId());
		if (access == null || !access.getEditable()) {
			throwSecurityException();
		}
		this.addOkOutcome(data);
		return data;
	}

}




/******* S.D.G. *******/



