/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.card.commands;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.card.data.ICardUpdatePriorityData;
import com.anfelisa.card.models.ICardModel;
import com.anfelisa.category.models.IUserAccessToCategoryModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class UpdateCardPriorityCommand extends AbstractUpdateCardPriorityCommand {

	static final Logger LOG = LoggerFactory.getLogger(UpdateCardPriorityCommand.class);

	public UpdateCardPriorityCommand(IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected ICardUpdatePriorityData executeCommand(ICardUpdatePriorityData data, PersistenceHandle readonlyHandle) {
		ICardModel card = daoProvider.getCardDao().selectByCardId(readonlyHandle, data.getCardId());
		if (card == null) {
			throwIllegalArgumentException("cardDoesNotExist");
		}
		IUserAccessToCategoryModel access = this.daoProvider.getUserAccessToCategoryDao()
				.selectByCategoryIdAndUserId(readonlyHandle, card.getRootCategoryId(), data.getUserId());
		if (access == null || !access.getEditable()) {
			throwSecurityException();
		}
		if (data.getPriority() != null
				&& (data.getPriority() < 1 || data.getPriority() > 3)) {
			throwIllegalArgumentException("invalidPriority");
		}
		this.addOkOutcome(data);
		return data;
	}

}




/******* S.D.G. *******/



