/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.changeorder.scenarios;

import com.anfelisa.category.data.ChangeOrderCategoryResponse;

@SuppressWarnings("unused")
public class ChangeOrderNoEditingAccessToMovedCategoryScenario extends AbstractChangeOrderNoEditingAccessToMovedCategoryScenario {

	

}




/******* S.D.G. *******/



