/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.changeorder.scenarios;

@SuppressWarnings("unused")
public class ChangeOrderNoEditingAccessToTargetCategoryScenario extends AbstractChangeOrderNoEditingAccessToTargetCategoryScenario {

	

}




/******* S.D.G. *******/



