/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.createbox.scenarios;

import com.anfelisa.box.data.CreateBoxResponse;

@SuppressWarnings("unused")
public class CreateBoxMinimalWithMaxCardsPerDayAndMaxIntervalScenario extends AbstractCreateBoxMinimalWithMaxCardsPerDayAndMaxIntervalScenario {

	

}




/******* S.D.G. *******/



