/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.createbox.scenarios;


public class CreateBoxMinimalWithMaxCardsPerDayAndMaxIntervalScenario extends AbstractCreateBoxMinimalWithMaxCardsPerDayAndMaxIntervalScenario {

	

}




/******* S.D.G. *******/



