/********************************************************************************
 * generated by de.acegen 1.0.1
 ********************************************************************************/




package com.anfelisa.card.getcards.scenarios;

@SuppressWarnings("unused")
public class GetFilteredCardsPriority1Scenario extends AbstractGetFilteredCardsPriority1Scenario {

	

}




/******* S.D.G. *******/



