/********************************************************************************
 * generated by de.acegen 1.0.1
 ********************************************************************************/




package com.anfelisa.card.getcards.scenarios;

import com.anfelisa.card.data.GetCardsResponse;

@SuppressWarnings("unused")
public class GetFilteredCardsScenario extends AbstractGetFilteredCardsScenario {

	

}




/******* S.D.G. *******/



