/********************************************************************************
 * generated by de.acegen 1.0.0
 ********************************************************************************/




package com.anfelisa.card.getcards.scenarios;

import com.anfelisa.card.data.GetCardsResponse;

@SuppressWarnings("unused")
public class GetNonActiveCardsScenario extends AbstractGetNonActiveCardsScenario {

	

}




/******* S.D.G. *******/



