/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.deletebox.scenarios;


public class DeleteBoxHasReverseBoxScenario extends AbstractDeleteBoxHasReverseBoxScenario {

	

}




/******* S.D.G. *******/



