/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.box.deletebox.scenarios;

import com.anfelisa.box.data.DeleteBoxResponse;

@SuppressWarnings("unused")
public class DeleteBoxNotMyCategoryScenario extends AbstractDeleteBoxNotMyCategoryScenario {

	

}




/******* S.D.G. *******/



