/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.deletebox.scenarios;


public class DeleteBoxSharedTwoUsersSpecialCaseScenario extends AbstractDeleteBoxSharedTwoUsersSpecialCaseScenario {

	

}




/******* S.D.G. *******/



