/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.deletebox.scenarios;

import com.anfelisa.box.data.DeleteBoxResponse;

@SuppressWarnings("unused")
public class DeleteBoxSharedEditableBoxOfOtherUserScenario extends AbstractDeleteBoxSharedEditableBoxOfOtherUserScenario {

	

}




/******* S.D.G. *******/



