/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.deletebox.scenarios;


public class DeleteBoxNotMyBoxScenario extends AbstractDeleteBoxNotMyBoxScenario {

	

}




/******* S.D.G. *******/



