/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.box.deletebox.scenarios;

@SuppressWarnings("unused")
public class DeleteReverseBoxScenario extends AbstractDeleteReverseBoxScenario {

	

}




/******* S.D.G. *******/



