/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.deletebox.scenarios;


public class DeleteBoxSharedEditableBoxOfMyselfScenario extends AbstractDeleteBoxSharedEditableBoxOfMyselfScenario {

	

}




/******* S.D.G. *******/



