/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




package com.anfelisa.user.gettoken.scenarios;

import java.security.Key;

import com.anfelisa.user.data.GetTokenResponse;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jws;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.security.Keys;

@SuppressWarnings("unused")
public class GetTokenStudentScenario extends AbstractGetTokenStudentScenario {

	@Override
	protected void validToken(GetTokenResponse response) {
		validateToken(response.getToken(), "uuid-" + this.getTestId(), "Annette-" + this.getTestId(), "STUDENT");
	}

	

}




/******* S.D.G. *******/



