/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




package com.anfelisa.user.gettoken.scenarios;

import com.anfelisa.user.data.GetTokenResponse;

@SuppressWarnings("unused")
public class GetTokenUnknownUserScenario extends AbstractGetTokenUnknownUserScenario {

	

}




/******* S.D.G. *******/



