/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.card.createcard.scenarios;

import com.anfelisa.card.data.CreateCardResponse;

@SuppressWarnings("unused")
public class CreateCardNoEditingAccessToCategoryScenario extends AbstractCreateCardNoEditingAccessToCategoryScenario {

	

}




/******* S.D.G. *******/



