/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.getboxes.scenarios;

import com.anfelisa.box.data.GetBoxesResponse;

@SuppressWarnings("unused")
public class GetBoxesSharedBoxOfOtherUserScenario extends AbstractGetBoxesSharedBoxOfOtherUserScenario {

	

}




/******* S.D.G. *******/



