/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




package com.anfelisa.box.getboxes.scenarios;

import com.anfelisa.box.data.GetBoxesResponse;

@SuppressWarnings("unused")
public class GetBoxesOneArchivedScenario extends AbstractGetBoxesOneArchivedScenario {

	

}




/******* S.D.G. *******/



