/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.box.getboxes.scenarios;

import com.anfelisa.box.data.GetBoxesResponse;

@SuppressWarnings("unused")
public class GetBoxesSharedScenario extends AbstractGetBoxesSharedScenario {

	

}




/******* S.D.G. *******/



