/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




package com.anfelisa.user.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class TokenData extends AbstractTokenData implements ITokenData {
	
	public TokenData(
		@JsonProperty("username") String username, 
		@JsonProperty("password") String password, 
		@JsonProperty("token") String token, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			username,
			password,
			token,
			uuid
		);
	}

	public TokenData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.user.models.ITokenModel generateTestData() {
		java.util.Random random = new java.util.Random();
		com.anfelisa.user.models.ITokenModel testData = new com.anfelisa.user.models.TokenModel();
		testData.setUsername(randomString(random));
		testData.setPassword(randomString(random));
		testData.setToken(randomString(random));
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



