/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.user.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UserListData extends AbstractUserListData implements IUserListData {
	
	public UserListData(
		@JsonProperty("userList") java.util.List<com.anfelisa.user.models.IUserModel> userList, 
		@JsonProperty("role") String role, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			userList,
			role,
			uuid
		);
	}

	public UserListData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.user.models.IUserListModel generateTestData() {
		java.util.Random random = new java.util.Random();
		int n;
		com.anfelisa.user.models.IUserListModel testData = new com.anfelisa.user.models.UserListModel();
		java.util.List<com.anfelisa.user.models.IUserModel> userListList = new java.util.ArrayList<com.anfelisa.user.models.IUserModel>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			userListList.add(com.anfelisa.user.data.UserData.generateTestData());
		}
		testData.setUserList(userListList);
		testData.setRole(randomString(random));
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



