/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.user.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UserData extends AbstractUserData implements IUserData {
	
	public UserData(
		@JsonProperty("userId") String userId, 
		@JsonProperty("username") String username, 
		@JsonProperty("password") String password, 
		@JsonProperty("email") String email, 
		@JsonProperty("role") String role, 
		@JsonProperty("emailConfirmed") Boolean emailConfirmed, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			userId,
			username,
			password,
			email,
			role,
			emailConfirmed,
			uuid
		);
	}

	public UserData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.user.models.IUserModel generateTestData() {
		java.util.Random random = new java.util.Random();
		com.anfelisa.user.models.IUserModel testData = new com.anfelisa.user.models.UserModel();
		testData.setUserId(randomString(random));
		testData.setUsername(randomString(random));
		testData.setPassword(randomString(random));
		testData.setEmail(randomString(random));
		testData.setRole(randomString(random));
		testData.setEmailConfirmed(new Boolean(random.nextBoolean()));
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



