/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.createcategory.scenarios;

@SuppressWarnings("unused")
public class CreateCategoryUnauthorizedNoEditingAccessScenario extends AbstractCreateCategoryUnauthorizedNoEditingAccessScenario {

	

}




/******* S.D.G. *******/



