/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.card.updatecardpriority.scenarios;

@SuppressWarnings("unused")
public class UpdateCardPriority4InvalidScenario extends AbstractUpdateCardPriority4InvalidScenario {

	

}




/******* S.D.G. *******/



