/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.card.updatecardpriority.scenarios;

@SuppressWarnings("unused")
public class UpdateCardPriorityUnauthorizedScenario extends AbstractUpdateCardPriorityUnauthorizedScenario {

	

}




/******* S.D.G. *******/



