/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.card.updatecardpriority.scenarios;

import com.anfelisa.card.data.UpdateCardPriorityResponse;

@SuppressWarnings("unused")
public class UpdateCardPriorityNoAccessToCardScenario extends AbstractUpdateCardPriorityNoAccessToCardScenario {

	

}




/******* S.D.G. *******/



