/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.card.updatecardpriority.scenarios;

import com.anfelisa.card.data.UpdateCardPriorityResponse;
import javax.ws.rs.core.Response;

@SuppressWarnings("unused")
public class UpdateCardPriorityUnauthorizedScenario extends AbstractUpdateCardPriorityUnauthorizedScenario {

	

}




/******* S.D.G. *******/



