/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.category.commands;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.category.models.CategoryChangeOrderModel;
import com.anfelisa.category.models.CategoryModel;
import com.anfelisa.category.models.UserAccessToCategoryModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.Data;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class ChangeOrderCategoryCommand extends AbstractChangeOrderCategoryCommand {

	static final Logger LOG = LoggerFactory.getLogger(ChangeOrderCategoryCommand.class);

	public ChangeOrderCategoryCommand(IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected Data<CategoryChangeOrderModel> executeCommand(Data<CategoryChangeOrderModel> data, PersistenceHandle readonlyHandle) {
		CategoryModel targetCategory = daoProvider.getCategoryDao().selectByCategoryId(readonlyHandle,
				data.getModel().getTargetCategoryId());
		if (targetCategory == null) {
			throwIllegalArgumentException("categoryDoesNotExist");
		}
		UserAccessToCategoryModel accessToRootCategory = this.daoProvider.getUserAccessToCategoryDao()
				.hasUserAccessTo(readonlyHandle, targetCategory.getRootCategoryId(), data.getModel().getUserId());
		if (accessToRootCategory == null || !accessToRootCategory.getEditable()) {
			throwSecurityException();
		}

		CategoryModel movedCategory = daoProvider.getCategoryDao().selectByCategoryId(readonlyHandle,
				data.getModel().getMovedCategoryId());
		if (movedCategory == null) {
			throwIllegalArgumentException("categoryDoesNotExist");
		}
		accessToRootCategory = this.daoProvider.getUserAccessToCategoryDao()
				.hasUserAccessTo(readonlyHandle, movedCategory.getRootCategoryId(), data.getModel().getUserId());
		if (accessToRootCategory == null || !accessToRootCategory.getEditable()) {
			throwSecurityException();
		}
		
		List<CategoryModel> categories = this.daoProvider.getCategoryDao().selectAllChildren(readonlyHandle,
				targetCategory.getParentCategoryId());
		int index = 1;
		for (CategoryModel category : categories) {
			if (category.getCategoryIndex() < targetCategory.getCategoryIndex()) {
				if (!data.getModel().getMovedCategoryId().equals(category.getCategoryId())) {
					category.setCategoryIndex(index);
					index++;
				}
			} else {
				break;
			}
		}
		for (CategoryModel category : categories) {
			if (data.getModel().getMovedCategoryId().equals(category.getCategoryId())) {
				category.setCategoryIndex(index);
				index++;
				break;
			}
		}
		for (CategoryModel category : categories) {
			if (category.getCategoryIndex() >= targetCategory.getCategoryIndex()) {
				if (!data.getModel().getMovedCategoryId().equals(category.getCategoryId())) {
					category.setCategoryIndex(index);
					index++;
				}
			}
		}
		data.getModel().setUpdatedIndices(categories);
		this.addOkOutcome(data);
		return data;
	}

}




/******* S.D.G. *******/



