/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.category.commands;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.category.data.ICategoryChangeOrderData;
import com.anfelisa.category.models.ICategoryModel;
import com.anfelisa.category.models.IUserAccessToCategoryModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class ChangeOrderCategoryCommand extends AbstractChangeOrderCategoryCommand {

	static final Logger LOG = LoggerFactory.getLogger(ChangeOrderCategoryCommand.class);

	public ChangeOrderCategoryCommand(IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected ICategoryChangeOrderData executeCommand(ICategoryChangeOrderData data, PersistenceHandle readonlyHandle) {
		ICategoryModel targetCategory = daoProvider.getCategoryDao().selectByCategoryId(readonlyHandle,
				data.getTargetCategoryId());
		if (targetCategory == null) {
			throwIllegalArgumentException("categoryDoesNotExist");
		}
		IUserAccessToCategoryModel accessToRootCategory = this.daoProvider.getUserAccessToCategoryDao()
				.hasUserAccessTo(readonlyHandle, targetCategory.getRootCategoryId(), data.getUserId());
		if (accessToRootCategory == null || !accessToRootCategory.getEditable()) {
			throwSecurityException();
		}

		ICategoryModel movedCategory = daoProvider.getCategoryDao().selectByCategoryId(readonlyHandle,
				data.getMovedCategoryId());
		if (movedCategory == null) {
			throwIllegalArgumentException("categoryDoesNotExist");
		}
		accessToRootCategory = this.daoProvider.getUserAccessToCategoryDao()
				.hasUserAccessTo(readonlyHandle, movedCategory.getRootCategoryId(), data.getUserId());
		if (accessToRootCategory == null || !accessToRootCategory.getEditable()) {
			throwSecurityException();
		}
		
		List<ICategoryModel> categories = this.daoProvider.getCategoryDao().selectAllChildren(readonlyHandle,
				targetCategory.getParentCategoryId());
		int index = 1;
		for (ICategoryModel category : categories) {
			if (category.getCategoryIndex() < targetCategory.getCategoryIndex()) {
				if (!data.getMovedCategoryId().equals(category.getCategoryId())) {
					category.setCategoryIndex(index);
					index++;
				}
			} else {
				break;
			}
		}
		for (ICategoryModel category : categories) {
			if (data.getMovedCategoryId().equals(category.getCategoryId())) {
				category.setCategoryIndex(index);
				index++;
				break;
			}
		}
		for (ICategoryModel category : categories) {
			if (category.getCategoryIndex() >= targetCategory.getCategoryIndex()) {
				if (!data.getMovedCategoryId().equals(category.getCategoryId())) {
					category.setCategoryIndex(index);
					index++;
				}
			}
		}
		data.setUpdatedIndices(categories);
		this.addOkOutcome(data);
		return data;
	}

}




/******* S.D.G. *******/



