/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.category.commands;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.category.data.ICategoryCreationData;
import com.anfelisa.category.models.ICategoryModel;
import com.anfelisa.category.models.IUserAccessToCategoryModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class CreateCategoryCommand extends AbstractCreateCategoryCommand {

	static final Logger LOG = LoggerFactory.getLogger(CreateCategoryCommand.class);

	public CreateCategoryCommand(IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected ICategoryCreationData executeCommand(ICategoryCreationData data, PersistenceHandle readonlyHandle) {
		ICategoryModel parentCategory = this.daoProvider.getCategoryDao().selectByCategoryId(readonlyHandle,
				data.getParentCategoryId());
		IUserAccessToCategoryModel access = this.daoProvider.getUserAccessToCategoryDao()
				.selectByCategoryIdAndUserId(readonlyHandle, parentCategory.getRootCategoryId(),
						data.getUserId());
		if (access == null || !access.getEditable()) {
			throwSecurityException();
		}
		data.setRootCategoryId(parentCategory.getRootCategoryId());
		data.setCategoryId(data.getUuid());
		data.setCategoryAuthor(data.getUsername());

		ICategoryModel rootCategory = this.daoProvider.getCategoryDao().selectByCategoryId(readonlyHandle,
				parentCategory.getRootCategoryId());

		data.setDictionaryLookup(rootCategory.getDictionaryLookup());
		data.setGivenLanguage(rootCategory.getGivenLanguage());
		data.setWantedLanguage(rootCategory.getWantedLanguage());

		Integer max = this.daoProvider.getCategoryDao().selectMaxIndexInCategory(readonlyHandle,
				data.getParentCategoryId());
		if (max == null) {
			max = 0;
		}
		data.setCategoryIndex(max + 1);
		this.addOkOutcome(data);
		return data;
	}

}




/******* S.D.G. *******/



