/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.commands;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.box.models.BoxModel;
import com.anfelisa.box.models.IBoxModel;
import com.anfelisa.category.data.IUserToCategoryInvitationData;
import com.anfelisa.category.models.ICategoryModel;
import com.anfelisa.category.models.IUserAccessToCategoryModel;
import com.anfelisa.user.models.IUserModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class InviteUserToCategoryCommand extends AbstractInviteUserToCategoryCommand {

	static final Logger LOG = LoggerFactory.getLogger(InviteUserToCategoryCommand.class);

	public InviteUserToCategoryCommand(IUserToCategoryInvitationData commandData, IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(commandData, daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected void executeCommand(PersistenceHandle readonlyHandle) {
		ICategoryModel category = daoProvider.getCategoryDao().selectByCategoryId(readonlyHandle, 
				commandData.getCategoryId());
		if (category == null) {
			throwIllegalArgumentException("categoryDoesNotExist");
		}

		IUserModel invitedUser = this.daoProvider.getUserDao().selectByUsername(readonlyHandle, commandData.getInvitedUsername());
		if (invitedUser == null) {
			this.throwIllegalArgumentException("userDoesNotExist");
		} else {
			commandData.setInvitedUserId(invitedUser.getUserId());
		}
		
		if (invitedUser.getUserId().equals(commandData.getUserId())) {
			this.throwIllegalArgumentException("userCannotInviteHimself");
		}
		
		IUserAccessToCategoryModel access = this.daoProvider.getUserAccessToCategoryDao().selectByCategoryIdAndUserId(readonlyHandle, commandData.getCategoryId(), commandData.getUserId());
		if (access == null || !access.getEditable()) {
			throwSecurityException();
		}
		
		IUserAccessToCategoryModel alreadyExistingAccess = this.daoProvider.getUserAccessToCategoryDao().selectByCategoryIdAndUserId(readonlyHandle, commandData.getCategoryId(), invitedUser.getUserId());
		if (alreadyExistingAccess != null) {
			throwIllegalArgumentException("userIsAlreadyInvited");
		}
		
		IBoxModel boxForInvitedUser = new BoxModel();
		boxForInvitedUser.setBoxId(commandData.getUuid());
		boxForInvitedUser.setCategoryId(commandData.getCategoryId());
		boxForInvitedUser.setMaxCardsPerDay(10);
		boxForInvitedUser.setUserId(invitedUser.getUserId());
		this.commandData.setBoxForInvitedUser(boxForInvitedUser);
		
		this.addOkOutcome();
	}

}




/******* S.D.G. *******/



