/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.commands;

import de.acegen.ViewProvider;
import de.acegen.IDaoProvider;
import de.acegen.CustomAppConfiguration;
import de.acegen.PersistenceHandle;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.category.data.IUserToCategoryInvitationData;
import com.anfelisa.category.models.ICategoryModel;
import com.anfelisa.category.models.IUserAccessToCategoryModel;
import com.anfelisa.user.models.IUserModel;

public class InviteUserToCategoryCommand extends AbstractInviteUserToCategoryCommand {

	static final Logger LOG = LoggerFactory.getLogger(InviteUserToCategoryCommand.class);

	public InviteUserToCategoryCommand(IUserToCategoryInvitationData commandData, IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(commandData, daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected void executeCommand(PersistenceHandle readonlyHandle) {
		IUserModel invitedUser = this.daoProvider.getUserDao().selectByUsername(readonlyHandle, commandData.getInvitedUsername());
		if (invitedUser == null) {
			this.throwIllegalArgumentException("userDoesNotExist");
		} else {
			commandData.setInvitedUserId(invitedUser.getUserId());
		}
		
		if (invitedUser.getUserId().equals(commandData.getUserId())) {
			this.throwIllegalArgumentException("userCannotInviteHimself");
		}
		
		IUserAccessToCategoryModel access = this.daoProvider.getUserAccessToCategoryDao().selectByCategoryIdAndUserId(readonlyHandle, commandData.getCategoryId(), commandData.getUserId());
		if (access == null || !access.getEditable()) {
			throwSecurityException();
		}
		
		ICategoryModel category = daoProvider.getCategoryDao().selectByCategoryId(readonlyHandle, 
				commandData.getCategoryId());
		if (category == null) {
			throwIllegalArgumentException("categoryDoesNotExist");
		}

		this.addOkOutcome();
	}

}




/******* S.D.G. *******/



