/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.card.importcsv.scenarios;

import com.anfelisa.card.data.ImportCsvResponse;

@SuppressWarnings("unused")
public class ImportCsvNoEditingAccessToCategoryScenario extends AbstractImportCsvNoEditingAccessToCategoryScenario {

	

}




/******* S.D.G. *******/



