/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




package com.anfelisa.box.actions;

import de.acegen.CustomAppConfiguration;
import de.acegen.ViewProvider;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ArchiveBoxAction extends AbstractArchiveBoxAction {

	static final Logger LOG = LoggerFactory.getLogger(ArchiveBoxAction.class);

	public ArchiveBoxAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration, IDaoProvider daoProvider, 
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}


	

}



/******* S.D.G. *******/



