/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.box.actions;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;
import de.acegen.ViewProvider;

public class CreateReverseBoxAction extends AbstractCreateReverseBoxAction {

	static final Logger LOG = LoggerFactory.getLogger(CreateReverseBoxAction.class);

	public CreateReverseBoxAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration, IDaoProvider daoProvider, 
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}


	
	public void initActionData() {
		// init not replayable data here
	}

}




/******* S.D.G. *******/



