/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.box.actions;

import java.time.LocalDateTime;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.box.data.IBoxStatisticsListData;
import com.anfelisa.box.models.IBoxStatisticsModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class GetBoxStatisticsAction extends AbstractGetBoxStatisticsAction {

	static final Logger LOG = LoggerFactory.getLogger(GetBoxStatisticsAction.class);

	public GetBoxStatisticsAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration, IDaoProvider daoProvider, 
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}


	@Override
	protected IBoxStatisticsListData loadDataForGetRequest(IBoxStatisticsListData data, PersistenceHandle readonlyHandle) {
		List<IBoxStatisticsModel> boxList = this.daoProvider.getBoxDao().selectStatisticsByUserId(readonlyHandle,
				data.getUserId());
		LocalDateTime today = data.getSystemTime().minusDays(1);
		for (IBoxStatisticsModel box : boxList) {
			List<Integer> countOfDay = this.daoProvider.getBoxDao().selectCountOfDay(readonlyHandle, box.getBoxId(), today);
			box.setCountsPerDayNextWeek(countOfDay);
		}
		data.setBoxStatisticsList(boxList);
		return data;
	}
	

}



/******* S.D.G. *******/



