/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.box.actions;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.box.models.IBoxModel;
import com.anfelisa.box.models.IBoxSettingsModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class GetBoxSettingsAction extends AbstractGetBoxSettingsAction {

	static final Logger LOG = LoggerFactory.getLogger(GetBoxSettingsAction.class);

	public GetBoxSettingsAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration, IDaoProvider daoProvider, 
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}


	@Override
	protected void loadDataForGetRequest(PersistenceHandle readonlyHandle) {
		IBoxModel box = daoProvider.getBoxDao().selectByBoxId(readonlyHandle, this.actionData.getBoxId());
		if (!box.getUserId().equals(actionData.getUserId())) {
			throwSecurityException();
		}
		IBoxSettingsModel settings = this.daoProvider.getBoxDao().selectSettingsByBoxId(readonlyHandle,
				actionData.getBoxId());
		this.actionData.setMaxCardsPerDay(settings.getMaxCardsPerDay());
		this.actionData.setMaxInterval(settings.getMaxInterval());
		this.actionData.setCategoryId(settings.getCategoryId());
		this.actionData.setCategoryName(settings.getCategoryName());
		this.actionData.setDictionaryLookup(settings.getDictionaryLookup());
		this.actionData.setGivenLanguage(settings.getGivenLanguage());
		this.actionData.setWantedLanguage(settings.getWantedLanguage());
		this.actionData.setAllActiveCards(settings.getAllActiveCards());
		this.actionData.setAllCards(settings.getAllCards());
		this.actionData.setShared(settings.getShared());
	}
	
	public void initActionData() {
		// init not replayable data here
	}

}




/******* S.D.G. *******/



