/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/

package com.anfelisa.box.actions;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.box.models.BoxStatisticsListModel;
import com.anfelisa.box.models.BoxStatisticsModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.Data;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class GetBoxStatisticsAction extends AbstractGetBoxStatisticsAction {

	static final Logger LOG = LoggerFactory.getLogger(GetBoxStatisticsAction.class);

	public GetBoxStatisticsAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration,
			IDaoProvider daoProvider, ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}

	@Override
	protected Data<BoxStatisticsListModel> loadDataForGetRequest(Data<BoxStatisticsListModel> data,
			PersistenceHandle readonlyHandle) {
		List<BoxStatisticsModel> boxList = this.daoProvider.getBoxDao().selectStatisticsByUserId(readonlyHandle,
				data.getModel().getUserId());
		for (BoxStatisticsModel box : boxList) {
			List<Integer> countOfDay = this.daoProvider.getBoxDao().selectCountOfDay(readonlyHandle, box.getBoxId(),
					data.getModel().getTodayAtMidnightInUTC());
			box.setCountsPerDayNextWeek(countOfDay);
		}
		data.getModel().setBoxStatisticsList(boxList);
		return data;
	}

}

/******* S.D.G. *******/
