/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/

package com.anfelisa.box.actions;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.box.data.IBoxSettingsWrapperData;
import com.anfelisa.box.models.IBoxModel;
import com.anfelisa.box.models.IBoxSettingsModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class GetBoxSettingsAction extends AbstractGetBoxSettingsAction {

	static final Logger LOG = LoggerFactory.getLogger(GetBoxSettingsAction.class);

	public GetBoxSettingsAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration,
			IDaoProvider daoProvider,
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}

	@Override
	protected IBoxSettingsWrapperData loadDataForGetRequest(IBoxSettingsWrapperData data,
			PersistenceHandle readonlyHandle) {
		IBoxModel box = daoProvider.getBoxDao().selectByBoxId(readonlyHandle, data.getBoxId());
		if (!box.getUserId().equals(data.getUserId())) {
			throwSecurityException();
		}
		IBoxSettingsModel settings = this.daoProvider.getBoxDao().selectSettingsByBoxId(readonlyHandle,
				data.getBoxId());
		data.setBoxSettings(settings);
		return data;
	}

}

/******* S.D.G. *******/
