/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.box.actions;

import org.slf4j.LoggerFactory;
import org.slf4j.Logger;

import com.anfelisa.box.data.INextCardData;
import com.anfelisa.box.models.IBoxModel;
import com.anfelisa.box.models.INextCardViewModel;
import com.anfelisa.box.models.ITodaysCardsStatusModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class LoadNextCardAction extends AbstractLoadNextCardAction {

	static final Logger LOG = LoggerFactory.getLogger(LoadNextCardAction.class);

	public LoadNextCardAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration, IDaoProvider daoProvider, 
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}


	@Override
	protected INextCardData loadDataForGetRequest(INextCardData data, PersistenceHandle readonlyHandle) {
		IBoxModel box = daoProvider.getBoxDao().selectByBoxId(readonlyHandle, data.getBoxId());
		if (box == null) {
			throwIllegalArgumentException("boxDoesNotExist");
		}
		if (!box.getUserId().equals(data.getUserId())) {
			throwSecurityException();
		}
		data.setReverse(box.getReverse());

		INextCardViewModel nextCard = daoProvider.getScheduledCardDao().selectFirstScheduledCard(readonlyHandle,
				data.getBoxId(), data.getTodayAtMidnightInUTC());
		if (nextCard == null) {
			nextCard = daoProvider.getReinforceCardDao().selectFirstReinforceCard(readonlyHandle,
					data.getBoxId());
		}
		if (nextCard != null) {
			data.mapFrom(nextCard);
			if (box.getReverse()) {
				data.setGiven(nextCard.getWanted());
				data.setWanted(nextCard.getGiven());
			}
		}
		ITodaysCardsStatusModel todaysCardsStatus = daoProvider.getBoxDao().todaysCardsStatus(readonlyHandle, box.getBoxId(), data.getTodayAtMidnightInUTC());
		data.setAllTodaysCards(todaysCardsStatus.getAllTodaysCards());
		data.setOpenTodaysCards(todaysCardsStatus.getOpenTodaysCards());
		return data;
	}
	

}



/******* S.D.G. *******/



