/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/

package com.anfelisa.box.actions;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.box.data.IActiveCardListData;
import com.anfelisa.box.models.IBoxModel;
import com.anfelisa.box.models.ICardWithStatisticsModel;
import com.anfelisa.category.models.IUserAccessToCategoryModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class LoadAllActiveCardsAction extends AbstractLoadAllActiveCardsAction {

	static final Logger LOG = LoggerFactory.getLogger(LoadAllActiveCardsAction.class);

	public LoadAllActiveCardsAction(PersistenceConnection persistenceConnection,
			CustomAppConfiguration appConfiguration, IDaoProvider daoProvider,
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}

	@Override
	protected IActiveCardListData loadDataForGetRequest(IActiveCardListData data, PersistenceHandle readonlyHandle) {
		IBoxModel box = daoProvider.getBoxDao().selectByBoxId(readonlyHandle, data.getBoxId());
		if (box == null) {
			throwIllegalArgumentException("boxDoesNotExist");
		}
		if (!box.getUserId().equals(data.getUserId())) {
			throwSecurityException();
		}

		List<ICardWithStatisticsModel> allCards = daoProvider.getCardDao().selectAllActiveCards(readonlyHandle,
				data.getBoxId());
		data.setCardList(allCards);

		IUserAccessToCategoryModel access = daoProvider.getUserAccessToCategoryDao()
				.selectByCategoryIdAndUserId(readonlyHandle, box.getCategoryId(), data.getUserId());
		data.setEditable(access.getEditable());
		return data;
	}

}

/******* S.D.G. *******/
