/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.box.actions;

import de.acegen.CustomAppConfiguration;
import de.acegen.ViewProvider;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class UpdateBoxAction extends AbstractUpdateBoxAction {

	static final Logger LOG = LoggerFactory.getLogger(UpdateBoxAction.class);

	public UpdateBoxAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration, IDaoProvider daoProvider, 
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}


	

}



/******* S.D.G. *******/



