/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.views;

import com.anfelisa.category.data.IUserToCategoryInvitationData;

import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;

public class BoxInvitationView implements IBoxInvitationView {

	private IDaoProvider daoProvider;
	
	public BoxInvitationView(IDaoProvider daoProvider) {
		super();
		this.daoProvider = daoProvider;
	}

	public void createBox(IUserToCategoryInvitationData data, PersistenceHandle handle) {
		daoProvider.getBoxDao().insert(handle, data.getBoxForInvitedUser());
	}

}




/******* S.D.G. *******/



