/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.views;

import com.anfelisa.category.data.IUserToCategoryInvitationData;

import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;

public class UserAccessToCategoryInvitationView implements IUserAccessToCategoryInvitationView {

	private IDaoProvider daoProvider;
	
	public UserAccessToCategoryInvitationView(IDaoProvider daoProvider) {
		super();
		this.daoProvider = daoProvider;
	}

	public void invite(IUserToCategoryInvitationData data, PersistenceHandle handle) {
		daoProvider.getUserAccessToCategoryDao().invite(handle, data);
	}

	@Override
	public void changeEditable(IUserToCategoryInvitationData data, PersistenceHandle handle) {
		daoProvider.getUserAccessToCategoryDao().changeEditable(handle, data);
	}

}




/******* S.D.G. *******/



