/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.views;

import com.anfelisa.category.models.UserToCategoryInvitationModel;

import de.acegen.Data;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;

public class UserAccessToCategoryInvitationView implements IUserAccessToCategoryInvitationView {

	private IDaoProvider daoProvider;
	
	public UserAccessToCategoryInvitationView(IDaoProvider daoProvider) {
		super();
		this.daoProvider = daoProvider;
	}

	public void invite(Data<UserToCategoryInvitationModel> data, PersistenceHandle handle) {
		daoProvider.getUserAccessToCategoryDao().invite(handle, data.getModel());
	}

	@Override
	public void changeEditable(Data<UserToCategoryInvitationModel> data, PersistenceHandle handle) {
		daoProvider.getUserAccessToCategoryDao().changeEditable(handle, data.getModel());
	}

}




/******* S.D.G. *******/



