/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.box.updatebox.scenarios;

import com.anfelisa.box.data.UpdateBoxResponse;

@SuppressWarnings("unused")
public class InvitedUserCannotChangeNameAndDistionaryLookupScenario extends AbstractInvitedUserCannotChangeNameAndDistionaryLookupScenario {

	

}




/******* S.D.G. *******/



