/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.actions;

import de.acegen.CustomAppConfiguration;
import de.acegen.ViewProvider;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;
import de.acegen.PersistenceHandle;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.category.models.ICategoryModel;
import com.anfelisa.category.models.IUserAccessToCategoryModel;

public class GetInvitedUsersAction extends AbstractGetInvitedUsersAction {

	static final Logger LOG = LoggerFactory.getLogger(GetInvitedUsersAction.class);

	public GetInvitedUsersAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration, IDaoProvider daoProvider, 
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}


	@Override
	protected void loadDataForGetRequest(PersistenceHandle readonlyHandle) {
		ICategoryModel category = daoProvider.getCategoryDao().selectByCategoryId(readonlyHandle, actionData.getCategoryId());
		if (category == null) {
			throwIllegalArgumentException("categoryDoesNotExist");
		}
		
		IUserAccessToCategoryModel access = daoProvider.getUserAccessToCategoryDao().selectByCategoryIdAndUserId(readonlyHandle, actionData.getCategoryId(), actionData.getUserId());
		if (access == null || !access.getEditable()) {
			throwSecurityException();
		}
		
		List<String> invitedUsernames = daoProvider.getUserAccessToCategoryDao().selectAllInvitedUsernames(readonlyHandle, actionData.getCategoryId());
		actionData.setInvitedUsernames(invitedUsernames);
	}
	
	public void initActionData() {
		// init not replayable data here
	}

}




/******* S.D.G. *******/



