/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.category.actions;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.category.models.AlreadyInvitedUsernamesModel;
import com.anfelisa.category.models.CategoryModel;
import com.anfelisa.category.models.UserAccessToCategoryModel;
import com.anfelisa.category.models.UsernameEditableModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.Data;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class GetInvitedUsersAction extends AbstractGetInvitedUsersAction {

	static final Logger LOG = LoggerFactory.getLogger(GetInvitedUsersAction.class);

	public GetInvitedUsersAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration, IDaoProvider daoProvider, 
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}


	@Override
	protected Data<AlreadyInvitedUsernamesModel> loadDataForGetRequest(Data<AlreadyInvitedUsernamesModel> data, PersistenceHandle readonlyHandle) {
		CategoryModel category = daoProvider.getCategoryDao().selectByCategoryId(readonlyHandle, data.getModel().getCategoryId());
		if (category == null) {
			throwIllegalArgumentException("categoryDoesNotExist");
		}
		
		UserAccessToCategoryModel access = daoProvider.getUserAccessToCategoryDao().selectByCategoryIdAndUserId(readonlyHandle, data.getModel().getCategoryId(), data.getModel().getUserId());
		if (access == null || !access.getEditable()) {
			throwSecurityException();
		}
		
		List<UsernameEditableModel> invitedUsers = daoProvider.getUserAccessToCategoryDao().selectAllInvitedUsers(readonlyHandle, data.getModel().getCategoryId(), data.getModel().getUserId());
		data.getModel().setInvitedUsers(invitedUsers);
		return data;
	}
	

}



/******* S.D.G. *******/



