/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.category.actions;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.category.data.IUsernameSearchData;
import com.anfelisa.category.models.IUserAccessToCategoryModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class SearchUsernameForInvitationAction extends AbstractSearchUsernameForInvitationAction {

	static final Logger LOG = LoggerFactory.getLogger(SearchUsernameForInvitationAction.class);

	public SearchUsernameForInvitationAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration, IDaoProvider daoProvider, 
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}


	@Override
	protected IUsernameSearchData loadDataForGetRequest(IUsernameSearchData data, PersistenceHandle readonlyHandle) {
		IUserAccessToCategoryModel access = daoProvider.getUserAccessToCategoryDao().selectByCategoryIdAndUserId(readonlyHandle, data.getCategoryId(), data.getUserId());
		if (access == null || !access.getEditable()) {
			throwSecurityException();
		}
		List<String> usernames = daoProvider.getCategoryDao().search(readonlyHandle, data.getUsernameSearchString(), data.getCategoryId());
		data.setUsernames(usernames);
		return data;
	}
	

}



/******* S.D.G. *******/



