/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.category.actions;

import de.acegen.CustomAppConfiguration;
import de.acegen.ViewProvider;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ToggleCategoryOrderAction extends AbstractToggleCategoryOrderAction {

	static final Logger LOG = LoggerFactory.getLogger(ToggleCategoryOrderAction.class);

	public ToggleCategoryOrderAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration, IDaoProvider daoProvider, 
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}


	

}



/******* S.D.G. *******/



