/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.getcategorytree.scenarios;

@SuppressWarnings("unused")
public class GetCategoryTreeInvitedUserScenario extends AbstractGetCategoryTreeInvitedUserScenario {

	

}




/******* S.D.G. *******/



