/********************************************************************************
 * generated by de.acegen 1.0.1
 ********************************************************************************/




package com.anfelisa.category.getcategorytree.scenarios;

@SuppressWarnings("unused")
public class GetCategoryTreeFilterIsNullScenario extends AbstractGetCategoryTreeFilterIsNullScenario {

	

}




/******* S.D.G. *******/



