/********************************************************************************
 * generated by de.acegen 1.0.0
 ********************************************************************************/




package com.anfelisa.category.getcategorytree.scenarios;

import com.anfelisa.category.data.GetCategoryTreeResponse;

@SuppressWarnings("unused")
public class GetCategoryTreeNoAccessScenario extends AbstractGetCategoryTreeNoAccessScenario {

	

}




/******* S.D.G. *******/



