/********************************************************************************
 * generated by de.acegen 1.0.0
 ********************************************************************************/




package com.anfelisa.category.getcategorytree.scenarios;

@SuppressWarnings("unused")
public class GetCategoryTreeUnauthorizedScenario extends AbstractGetCategoryTreeUnauthorizedScenario {

	

}




/******* S.D.G. *******/



