/********************************************************************************
 * generated by de.acegen 1.0.1
 ********************************************************************************/




package com.anfelisa.category.getcategorytree.scenarios;

import com.anfelisa.category.data.GetCategoryTreeResponse;

@SuppressWarnings("unused")
public class GetFilteredCategoryPriority3TreeScenario extends AbstractGetFilteredCategoryPriority3TreeScenario {

	

}




/******* S.D.G. *******/



