/********************************************************************************
 * generated by de.acegen 1.0.1
 ********************************************************************************/




package com.anfelisa.category.getcategorytree.scenarios;

@SuppressWarnings("unused")
public class GetFilteredCategoryPriority2TreeScenario extends AbstractGetFilteredCategoryPriority2TreeScenario {

	

}




/******* S.D.G. *******/



