/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.box.loadallactivecards.scenarios;

@SuppressWarnings("unused")
public class LoadAllActiveCardsWithPriorityScenario extends AbstractLoadAllActiveCardsWithPriorityScenario {

	

}




/******* S.D.G. *******/



