/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.box.loadallactivecards.scenarios;

@SuppressWarnings("unused")
public class LoadAllActiveCardsBoxDoesNotExistScenario extends AbstractLoadAllActiveCardsBoxDoesNotExistScenario {

	

}




/******* S.D.G. *******/



