/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.box.loadallactivecards.scenarios;

import com.anfelisa.box.data.LoadAllActiveCardsResponse;

@SuppressWarnings("unused")
public class LoadAllActiveCardsWithScored0Scenario extends AbstractLoadAllActiveCardsWithScored0Scenario {

	

}




/******* S.D.G. *******/



