/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.card.changeorder.scenarios;


public class ChangeOrderUpScenario extends AbstractChangeOrderUpScenario {

	

}




/******* S.D.G. *******/



