/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.card.changeorder.scenarios;

import com.anfelisa.card.data.ChangeOrderResponse;

@SuppressWarnings("unused")
public class ChangeOrderNoEditingAccessToMovedCardScenario extends AbstractChangeOrderNoEditingAccessToMovedCardScenario {

	

}




/******* S.D.G. *******/



