/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.card.changeorder.scenarios;

@SuppressWarnings("unused")
public class ChangeOrderNoEditingAccessToTargetCardScenario extends AbstractChangeOrderNoEditingAccessToTargetCardScenario {

	

}




/******* S.D.G. *******/



