/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.card.changeorder.scenarios;


public class NoMoveUpScenario extends AbstractNoMoveUpScenario {

	

}




/******* S.D.G. *******/



