/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.box.createreversebox.scenarios;

@SuppressWarnings("unused")
public class CreateReverseBoxBoxDoesNotExistScenario extends AbstractCreateReverseBoxBoxDoesNotExistScenario {

	

}




/******* S.D.G. *******/



