/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.createreversebox.scenarios;

import com.anfelisa.box.data.CreateReverseBoxResponse;

@SuppressWarnings("unused")
public class CreateReverseBoxSecondTimeScenario extends AbstractCreateReverseBoxSecondTimeScenario {

	

}




/******* S.D.G. *******/



