/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.createreversebox.scenarios;


public class CreateReverseBoxAlreadyExistsScenario extends AbstractCreateReverseBoxAlreadyExistsScenario {

	

}




/******* S.D.G. *******/



