/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.box.createreversebox.scenarios;

import com.anfelisa.box.data.CreateReverseBoxResponse;

@SuppressWarnings("unused")
public class CreateReverseBoxScenario extends AbstractCreateReverseBoxScenario {

	

}




/******* S.D.G. *******/



