/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.card.actions;

import de.acegen.CustomAppConfiguration;
import de.acegen.ViewProvider;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ChangeOrderAction extends AbstractChangeOrderAction {

	static final Logger LOG = LoggerFactory.getLogger(ChangeOrderAction.class);

	public ChangeOrderAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration, IDaoProvider daoProvider, 
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}


	

}



/******* S.D.G. *******/



