/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.card.actions;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.card.models.CardSearchModel;
import com.anfelisa.card.models.CardWithCategoryNameModel;
import com.anfelisa.category.models.CategoryModel;
import com.anfelisa.category.models.UserAccessToCategoryModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.Data;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class GetDuplicatesAction extends AbstractGetDuplicatesAction {

	static final Logger LOG = LoggerFactory.getLogger(GetDuplicatesAction.class);

	public GetDuplicatesAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration, IDaoProvider daoProvider, 
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}


	@Override
	protected Data<CardSearchModel> loadDataForGetRequest(Data<CardSearchModel> data, PersistenceHandle readonlyHandle) {
		if (data.getModel().getNaturalInputOrder() == null) {
			data.getModel().setNaturalInputOrder(false);
		}
		CategoryModel category = daoProvider.getCategoryDao().selectByCategoryId(readonlyHandle,
				data.getModel().getCategoryId());
		if (category == null) {
			throwIllegalArgumentException("categoryDoesNotExist");
		}
		UserAccessToCategoryModel userAccessToCategoryModel = daoProvider.getUserAccessToCategoryDao()
				.hasUserAccessTo(readonlyHandle, data.getModel().getCategoryId(), data.getModel().getUserId());
		if (userAccessToCategoryModel == null) {
			throwSecurityException();
		}
		List<CardWithCategoryNameModel> cardList = this.daoProvider.getCardDao().search(readonlyHandle, data.getModel().getCategoryId(),
				data.getModel().getNaturalInputOrder(), data.getModel().getGiven(), data.getModel().getWanted());
		data.getModel().setCardList(cardList);
		return data;
	}
	

}



/******* S.D.G. *******/



