/********************************************************************************
 * generated by de.acegen 1.6.5
 ********************************************************************************/




package com.anfelisa.card.actions;

import java.net.URL;
import java.net.URLEncoder;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.card.models.CardTranslationModel;
import com.fasterxml.jackson.databind.ObjectMapper;

import de.acegen.CustomAppConfiguration;
import de.acegen.Data;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceConnection;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class GetTranslationAction extends AbstractGetTranslationAction {

	static final Logger LOG = LoggerFactory.getLogger(GetTranslationAction.class);

	public GetTranslationAction(PersistenceConnection persistenceConnection, CustomAppConfiguration appConfiguration, IDaoProvider daoProvider, 
			ViewProvider viewProvider) {
		super(persistenceConnection, appConfiguration, daoProvider, viewProvider);
	}


	@Override
	@SuppressWarnings("unchecked")
	protected Data<CardTranslationModel> loadDataForGetRequest(Data<CardTranslationModel> data, PersistenceHandle readonlyHandle) {
		try {
			String translationApiKey = appConfiguration.getTranslationApiKey();
			String urlStr = "https://api-free.deepl.com/v2/translate?"
					+ "auth_key=" + translationApiKey +
					"&text=" + URLEncoder.encode(data.getModel().getSourceValue(), "UTF-8") +
					"&source_lang=" + data.getModel().getSourceLanguage().toUpperCase() +
					"&target_lang=" + data.getModel().getTargetLanguage().toUpperCase();
			URL url = new URL(urlStr);
			ObjectMapper mapper = new ObjectMapper();
			Map<String, Object> map = mapper.readValue(url, Map.class);
			List<Map<String, Object>> translations = (List<Map<String, Object>>) map.get("translations");
			for (Map<String, Object> translation : translations) {
				data.getModel().setTargetValue(translation.get("text").toString());
			}
		} catch (Exception e) {
			LOG.error(e.getMessage(), e);
			data.getModel().setTargetValue("");
		}
		return data;
	}
	

}



/******* S.D.G. *******/



