/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.card.deletecard.scenarios;

import com.anfelisa.card.data.DeleteCardResponse;

@SuppressWarnings("unused")
public class DeleteCardNoEditingAccessToCategoryScenario extends AbstractDeleteCardNoEditingAccessToCategoryScenario {

	

}




/******* S.D.G. *******/



