/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package de.acegen;

public class EventReplayService {
	public static void replayEvent(String eventClass, String json, PersistenceHandle handle, IDaoProvider daoProvider, ViewProvider viewProvider, CustomAppConfiguration appConfiguration) {
		if (eventClass.startsWith("com.anfelisa.box.events")) {
			com.anfelisa.box.events.EventReplayService.replayEvent(eventClass, json, handle, daoProvider, viewProvider, appConfiguration);
		}
		if (eventClass.startsWith("com.anfelisa.card.events")) {
			com.anfelisa.card.events.EventReplayService.replayEvent(eventClass, json, handle, daoProvider, viewProvider, appConfiguration);
		}
		if (eventClass.startsWith("com.anfelisa.category.events")) {
			com.anfelisa.category.events.EventReplayService.replayEvent(eventClass, json, handle, daoProvider, viewProvider, appConfiguration);
		}
		if (eventClass.startsWith("com.anfelisa.user.events")) {
			com.anfelisa.user.events.EventReplayService.replayEvent(eventClass, json, handle, daoProvider, viewProvider, appConfiguration);
		}
	}
}



/******* S.D.G. *******/



