/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package de.acegen;

public class EventFactory {
	public static IEvent<?> createEvent(String eventClass, String json, IDaoProvider daoProvider, ViewProvider viewProvider, CustomAppConfiguration appConfiguration) {
		//delegate to package EventFactory
		return null;
	}
	public static IEvent<?> createEvent(String eventClass, IDataContainer data, IDaoProvider daoProvider, ViewProvider viewProvider, CustomAppConfiguration appConfiguration) {
		//delegate to package EventFactory
		return null;
	}
}



/******* S.D.G. *******/



