/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package de.acegen;

public class EventReplayService {
	public static void replayEvent(String eventClass, String json, PersistenceHandle handle, ViewProvider viewProvider) {
		//delegate to package EventReplayService
	}
}



/******* S.D.G. *******/



