/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/

package de.acegen;

public class EventReplayService {
	public static void replayEvent(String eventClass, String json, PersistenceHandle handle, ViewProvider viewProvider) {
		if (eventClass.startsWith("com.anfelisa.box.events")) {
			com.anfelisa.box.events.EventReplayService.replayEvent(eventClass, json, handle, viewProvider);
		}
		if (eventClass.startsWith("com.anfelisa.card.events")) {
			com.anfelisa.card.events.EventReplayService.replayEvent(eventClass, json, handle, viewProvider);
		}
		if (eventClass.startsWith("com.anfelisa.category.events")) {
			com.anfelisa.category.events.EventReplayService.replayEvent(eventClass, json, handle, viewProvider);
		}
		if (eventClass.startsWith("com.anfelisa.user.events")) {
			com.anfelisa.user.events.EventReplayService.replayEvent(eventClass, json, handle, viewProvider);
		}
	}
}

/******* S.D.G. *******/
