/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.card.movecard.scenarios;

import com.anfelisa.card.data.MoveCardsResponse;

@SuppressWarnings("unused")
public class MoveCardsNoEditingAccessToCardScenario extends AbstractMoveCardsNoEditingAccessToCardScenario {

	

}




/******* S.D.G. *******/



