/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.card.movecard.scenarios;

@SuppressWarnings("unused")
public class MoveCardsNoEditingAccessToCardScenario extends AbstractMoveCardsNoEditingAccessToCardScenario {

	

}




/******* S.D.G. *******/



