/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.category.toggleorder.scenarios;


public class ToggleCategoryOrderNoEditingAccessToCategory1Scenario extends AbstractToggleCategoryOrderNoEditingAccessToCategory1Scenario {

	

}




/******* S.D.G. *******/



