/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.category.toggleorder.scenarios;


public class ToggleCategoryOrderUnauthorizedScenario extends AbstractToggleCategoryOrderUnauthorizedScenario {

	

}




/******* S.D.G. *******/



