/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.category.toggleorder.scenarios;


public class ToggleCategoryOrderNoAccessToCategory1Scenario extends AbstractToggleCategoryOrderNoAccessToCategory1Scenario {

	

}




/******* S.D.G. *******/



