/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.category.toggleorder.scenarios;


public class ToggleCategoryOrderDownScenario extends AbstractToggleCategoryOrderDownScenario {

	

}




/******* S.D.G. *******/



