/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class AlreadyInvitedUsernamesData extends AbstractAlreadyInvitedUsernamesData implements IAlreadyInvitedUsernamesData {
	
	public AlreadyInvitedUsernamesData(
		@JsonProperty("categoryId") String categoryId, 
		@JsonProperty("userId") String userId, 
		@JsonProperty("invitedUsernames") java.util.List<String> invitedUsernames, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			categoryId,
			userId,
			invitedUsernames,
			uuid
		);
	}

	public AlreadyInvitedUsernamesData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.category.models.IAlreadyInvitedUsernamesModel generateTestData() {
		java.util.Random random = new java.util.Random();
		int n;
		com.anfelisa.category.models.IAlreadyInvitedUsernamesModel testData = new com.anfelisa.category.models.AlreadyInvitedUsernamesModel();
		testData.setCategoryId(randomString(random));
		testData.setUserId(randomString(random));
		java.util.List<String> invitedUsernamesList = new java.util.ArrayList<String>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			invitedUsernamesList.add(randomString(random));
		}
		testData.setInvitedUsernames(invitedUsernamesList);
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



