/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CategoryMoveData extends AbstractCategoryMoveData implements ICategoryMoveData {
	
	public CategoryMoveData(
		@JsonProperty("movedCategoryId") String movedCategoryId, 
		@JsonProperty("targetCategoryId") String targetCategoryId, 
		@JsonProperty("movedCategory") com.anfelisa.category.models.ICategoryModel movedCategory, 
		@JsonProperty("categoryIndexWhereRemoved") Integer categoryIndexWhereRemoved, 
		@JsonProperty("parentCategoryIdWhereRemoved") String parentCategoryIdWhereRemoved, 
		@JsonProperty("userId") String userId, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			movedCategoryId,
			targetCategoryId,
			movedCategory,
			categoryIndexWhereRemoved,
			parentCategoryIdWhereRemoved,
			userId,
			uuid
		);
	}

	public CategoryMoveData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.category.models.ICategoryMoveModel generateTestData() {
		java.util.Random random = new java.util.Random();
		com.anfelisa.category.models.ICategoryMoveModel testData = new com.anfelisa.category.models.CategoryMoveModel();
		testData.setMovedCategoryId(randomString(random));
		testData.setTargetCategoryId(randomString(random));
		testData.setMovedCategory(com.anfelisa.category.data.CategoryData.generateTestData());
		testData.setCategoryIndexWhereRemoved(random.nextInt(50));
		testData.setParentCategoryIdWhereRemoved(randomString(random));
		testData.setUserId(randomString(random));
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



