/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CategoryChangeOrderData extends AbstractCategoryChangeOrderData implements ICategoryChangeOrderData {
	
	public CategoryChangeOrderData(
		@JsonProperty("movedCategoryId") String movedCategoryId, 
		@JsonProperty("targetCategoryId") String targetCategoryId, 
		@JsonProperty("userId") String userId, 
		@JsonProperty("updatedIndices") java.util.List<com.anfelisa.category.models.ICategoryModel> updatedIndices, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			movedCategoryId,
			targetCategoryId,
			userId,
			updatedIndices,
			uuid
		);
	}

	public CategoryChangeOrderData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.category.models.ICategoryChangeOrderModel generateTestData() {
		java.util.Random random = new java.util.Random();
		int n;
		com.anfelisa.category.models.ICategoryChangeOrderModel testData = new com.anfelisa.category.models.CategoryChangeOrderModel();
		testData.setMovedCategoryId(randomString(random));
		testData.setTargetCategoryId(randomString(random));
		testData.setUserId(randomString(random));
		java.util.List<com.anfelisa.category.models.ICategoryModel> updatedIndicesList = new java.util.ArrayList<com.anfelisa.category.models.ICategoryModel>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			updatedIndicesList.add(com.anfelisa.category.data.CategoryData.generateTestData());
		}
		testData.setUpdatedIndices(updatedIndicesList);
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



