/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UsernameSearchData extends AbstractUsernameSearchData implements IUsernameSearchData {
	
	public UsernameSearchData(
		@JsonProperty("usernameSearchString") String usernameSearchString, 
		@JsonProperty("userId") String userId, 
		@JsonProperty("categoryId") String categoryId, 
		@JsonProperty("usernames") java.util.List<String> usernames, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			usernameSearchString,
			userId,
			categoryId,
			usernames,
			uuid
		);
	}

	public UsernameSearchData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.category.models.IUsernameSearchModel generateTestData() {
		java.util.Random random = new java.util.Random();
		int n;
		com.anfelisa.category.models.IUsernameSearchModel testData = new com.anfelisa.category.models.UsernameSearchModel();
		testData.setUsernameSearchString(randomString(random));
		testData.setUserId(randomString(random));
		testData.setCategoryId(randomString(random));
		java.util.List<String> usernamesList = new java.util.ArrayList<String>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			usernamesList.add(randomString(random));
		}
		testData.setUsernames(usernamesList);
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



