/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.category.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UserAccessToCategoryData extends AbstractUserAccessToCategoryData implements IUserAccessToCategoryData {
	
	public UserAccessToCategoryData(
		@JsonProperty("categoryId") String categoryId, 
		@JsonProperty("userId") String userId, 
		@JsonProperty("editable") Boolean editable, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			categoryId,
			userId,
			editable,
			uuid
		);
	}

	public UserAccessToCategoryData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.category.models.IUserAccessToCategoryModel generateTestData() {
		java.util.Random random = new java.util.Random();
		com.anfelisa.category.models.IUserAccessToCategoryModel testData = new com.anfelisa.category.models.UserAccessToCategoryModel();
		testData.setCategoryId(randomString(random));
		testData.setUserId(randomString(random));
		testData.setEditable(random.nextBoolean());
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



