/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.category.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UserWithAccessListData extends AbstractUserWithAccessListData implements IUserWithAccessListData {
	
	public UserWithAccessListData(
		@JsonProperty("categoryId") String categoryId, 
		@JsonProperty("userList") java.util.List<com.anfelisa.category.models.IUserWithAccessModel> userList, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			categoryId,
			userList,
			uuid
		);
	}

	public UserWithAccessListData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.category.models.IUserWithAccessListModel generateTestData() {
		java.util.Random random = new java.util.Random();
		int n;
		com.anfelisa.category.models.IUserWithAccessListModel testData = new com.anfelisa.category.models.UserWithAccessListModel();
		testData.setCategoryId(randomString(random));
		java.util.List<com.anfelisa.category.models.IUserWithAccessModel> userListList = new java.util.ArrayList<com.anfelisa.category.models.IUserWithAccessModel>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			userListList.add(com.anfelisa.category.data.UserWithAccessData.generateTestData());
		}
		testData.setUserList(userListList);
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



