/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.getinvitedusernames.scenarios;

import com.anfelisa.category.data.GetInvitedUsersResponse;

@SuppressWarnings("unused")
public class GetInvitedUsersUnauthorizedScenario extends AbstractGetInvitedUsersUnauthorizedScenario {

	

}




/******* S.D.G. *******/



