/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.getinvitedusernames.scenarios;

@SuppressWarnings("unused")
public class GetInvitedUsersScenario extends AbstractGetInvitedUsersScenario {

	

}




/******* S.D.G. *******/



