/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.category.getinvitedusernames.scenarios;

import com.anfelisa.category.data.GetInvitedUsersResponse;

@SuppressWarnings("unused")
public class GetInvitedUsersEditableScenario extends AbstractGetInvitedUsersEditableScenario {

	

}




/******* S.D.G. *******/



