/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.scorecard.scenarios;

import com.anfelisa.box.data.ScoreCardResponse;

@SuppressWarnings("unused")
public class ScoreCard3WhenNIs2Scenario extends AbstractScoreCard3WhenNIs2Scenario {

	

}




/******* S.D.G. *******/



