/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.scorecard.scenarios;

public class ScoreMaxCardsPerDayScenario extends AbstractScoreMaxCardsPerDayScenario {

	

}




/******* S.D.G. *******/



