/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.scorecard.scenarios;

import com.anfelisa.box.data.UpdateBoxResponse;
import com.anfelisa.box.data.ScoreCardResponse;
import com.anfelisa.box.data.ScoreCardResponse;

@SuppressWarnings("unused")
public class ScoreMaxCardsPerDayScenario extends AbstractScoreMaxCardsPerDayScenario {

	

}




/******* S.D.G. *******/



