/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.scorecard.scenarios;

import com.anfelisa.box.data.ScoreCardResponse;

@SuppressWarnings("unused")
public class ScoreAlreadyScoredScenario extends AbstractScoreAlreadyScoredScenario {

	

}




/******* S.D.G. *******/



