/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.scorecard.scenarios;

import com.anfelisa.box.data.ScoreCardResponse;

@SuppressWarnings("unused")
public class ScoreCard3WhenNIs0Scenario extends AbstractScoreCard3WhenNIs0Scenario {

	

}




/******* S.D.G. *******/



