/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.user.getuserprofile.scenarios;

import com.anfelisa.user.data.GetUserProfileResponse;

@SuppressWarnings("unused")
public class GetUserProfileAdminWithSharedBoxWhenThereIsAnotherUserWithWriteAccessScenario extends AbstractGetUserProfileAdminWithSharedBoxWhenThereIsAnotherUserWithWriteAccessScenario {

	

}




/******* S.D.G. *******/



