/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.schedulecards.scenarios;

import com.anfelisa.box.data.ScheduleCardsResponse;

@SuppressWarnings("unused")
public class ScheduleCardsNullBoxIdScenario extends AbstractScheduleCardsNullBoxIdScenario {

	

}




/******* S.D.G. *******/



