/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.schedulecards.scenarios;


public class ScheduleCardsNullBoxIdScenario extends AbstractScheduleCardsNullBoxIdScenario {

	

}




/******* S.D.G. *******/



