/********************************************************************************
 * generated by de.acegen 1.0.0
 ********************************************************************************/




package com.anfelisa.box.getboxsettings.scenarios;

@SuppressWarnings("unused")
public class GetBoxSettingsWithCardsScenario extends AbstractGetBoxSettingsWithCardsScenario {

	

}




/******* S.D.G. *******/



