/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.box.getboxsettings.scenarios;

@SuppressWarnings("unused")
public class GetBoxSettingsWithSortedOutCardsScenario extends AbstractGetBoxSettingsWithSortedOutCardsScenario {

	

}




/******* S.D.G. *******/



