/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.box.getboxsettings.scenarios;

import com.anfelisa.box.data.GetBoxSettingsResponse;

@SuppressWarnings("unused")
public class GetSharedBoxSettingsEditableScenario extends AbstractGetSharedBoxSettingsEditableScenario {

	

}




/******* S.D.G. *******/



