/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.box.getboxsettings.scenarios;

import com.anfelisa.box.data.GetBoxSettingsResponse;

@SuppressWarnings("unused")
public class GetSharedBoxSettingsScenario extends AbstractGetSharedBoxSettingsScenario {

	

}




/******* S.D.G. *******/



