/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




package com.anfelisa.box.commands;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.box.models.BoxArchiveModel;
import com.anfelisa.box.models.BoxModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.Data;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class ArchiveBoxCommand extends AbstractArchiveBoxCommand {

	static final Logger LOG = LoggerFactory.getLogger(ArchiveBoxCommand.class);

	public ArchiveBoxCommand(IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected Data<BoxArchiveModel> executeCommand(Data<BoxArchiveModel> data, PersistenceHandle readonlyHandle) {
		if (data.getModel().getArchived() == null) {
			data.getModel().setArchived(false);
		}
		BoxModel box = daoProvider.getBoxDao().selectByBoxId(readonlyHandle, data.getModel().getBoxId());
		if (!box.getUserId().equals(data.getModel().getUserId())) {
			throwSecurityException();
		}
		this.addOkOutcome(data);
		return data;
	}

}




/******* S.D.G. *******/



