/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.box.commands;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.box.data.IBoxCreationData;
import com.anfelisa.box.models.IBoxModel;
import com.anfelisa.category.models.IUserAccessToCategoryModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class CreateReverseBoxCommand extends AbstractCreateReverseBoxCommand {

	static final Logger LOG = LoggerFactory.getLogger(CreateReverseBoxCommand.class);

	public CreateReverseBoxCommand(IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected IBoxCreationData executeCommand(IBoxCreationData data, PersistenceHandle readonlyHandle) {
		IUserAccessToCategoryModel access = this.daoProvider.getUserAccessToCategoryDao()
				.selectByCategoryIdAndUserId(readonlyHandle, data.getRootCategoryId(), data.getUserId());
		if (access == null) {
			throwSecurityException();
		}
		IBoxModel box = daoProvider.getBoxDao().selectByCategoryIdAndUserId(readonlyHandle, data.getRootCategoryId(), data.getUserId(), false);
		if (box == null) {
			throwIllegalArgumentException("boxNotFound");
		}

		IBoxModel reverseBox = daoProvider.getBoxDao().selectByCategoryIdAndUserId(readonlyHandle, data.getRootCategoryId(), data.getUserId(), true);
		if (reverseBox == null) {
			data.setCategoryId(box.getCategoryId());
			data.setMaxInterval(box.getMaxInterval());
			data.setMaxCardsPerDay(box.getMaxCardsPerDay());
			data.setReverse(true);
			data.setBoxId(data.getUuid());
			this.addOkOutcome(data);
		} else {
			this.addAlreadyExistsOutcome(data);
		}
		return data;
	}

}




/******* S.D.G. *******/



