/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/

package com.anfelisa.box.commands;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.box.data.IDeleteBoxData;
import com.anfelisa.box.models.IBoxModel;
import com.anfelisa.category.models.IUserAccessToCategoryModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class DeleteBoxCommand extends AbstractDeleteBoxCommand {

	static final Logger LOG = LoggerFactory.getLogger(DeleteBoxCommand.class);

	public DeleteBoxCommand(IDaoProvider daoProvider, ViewProvider viewProvider,
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected IDeleteBoxData executeCommand(IDeleteBoxData data, PersistenceHandle readonlyHandle) {
		IBoxModel box = daoProvider.getBoxDao().selectByBoxId(readonlyHandle, data.getBoxId());
		if (box == null) {
			throwIllegalArgumentException("boxDoesNotExist");
		}
		if (!box.getUserId().equals(data.getUserId())) {
			throwSecurityException();
		}
		IUserAccessToCategoryModel access = daoProvider.getUserAccessToCategoryDao()
				.selectByCategoryIdAndUserId(readonlyHandle, box.getCategoryId(), data.getUserId());
		if (access == null) {
			throwSecurityException();
		}
		if (access.getEditable() && !box.getReverse()) {
			data.setRootCategoryId(box.getCategoryId());
			List<IUserAccessToCategoryModel> accesses = daoProvider.getUserAccessToCategoryDao()
					.selectByCategoryIdAndNotMine(readonlyHandle, box.getCategoryId(), data.getUserId());
			if (accesses.size() > 0) {
				throwIllegalArgumentException("cannotDeleteSharedBox");
			}
			this.addDeleteCategoryOutcome(data);
		}
		this.addDeleteBoxOutcome(data);
		return data;
	}

}

/******* S.D.G. *******/
