/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/

package com.anfelisa.box.commands;

import java.util.ArrayList;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.box.models.BoxModel;
import com.anfelisa.box.models.ScheduledCardModel;
import com.anfelisa.box.models.ScheduledCardsModel;
import com.anfelisa.card.models.CardModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.Data;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class ScheduleCardsCommand extends AbstractScheduleCardsCommand {

	static final Logger LOG = LoggerFactory.getLogger(ScheduleCardsCommand.class);

	public ScheduleCardsCommand(IDaoProvider daoProvider, ViewProvider viewProvider,
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected Data<ScheduledCardsModel> executeCommand(Data<ScheduledCardsModel> data, PersistenceHandle readonlyHandle) {
		if (data.getModel().getCardIds() == null || data.getModel().getCardIds().size() == 0) {
			this.addNullOrEmptyOutcome(data);
		} else {
			data.getModel().setExistingScheduledCardIds(new ArrayList<String>());
			data.getModel().setNewScheduledCards(new ArrayList<ScheduledCardModel>());
			data.getModel().setScheduledDate(data.getSystemTime());
			BoxModel box = daoProvider.getBoxDao().selectByBoxId(readonlyHandle, data.getModel().getBoxId());
			if (box == null) {
				throwIllegalArgumentException("boxDoesNotExist");
			}
			if (!box.getUserId().equals(data.getModel().getUserId())) {
				throwSecurityException();
			}
			for (String cardId : data.getModel().getCardIds()) {
				CardModel card = daoProvider.getCardDao().selectByCardId(readonlyHandle, cardId);
				if (card == null) {
					throwIllegalArgumentException("cardDoesNotExist");
				}
				ScheduledCardModel scheduledCard = daoProvider.getScheduledCardDao()
						.selectUnscoredByCardIdAndBoxId(readonlyHandle, cardId, box.getBoxId());
				ScheduledCardModel newScheduledCard;
				if (scheduledCard == null) {
					newScheduledCard = new ScheduledCardModel(
							combineUuids(cardId, data.getUuid()), cardId, box.getBoxId(),
							data.getSystemTime(), 2.5F, 1, 1, 0, data.getSystemTime(), null,
							null, null);
					data.getModel().getNewScheduledCards().add(newScheduledCard);
				} else {
					data.getModel().getExistingScheduledCardIds().add(scheduledCard.getScheduledCardId());
				}
			}
			this.addOkOutcome(data);
		}
		return data;
	}

	private String combineUuids(String uuid1, String uuid2) {
		return (uuid1.length() >= 12 ? uuid1.substring(0, 12) : uuid1) + "-"
				+ (uuid2.length() >= 12 ? uuid2.substring(0, 12) : uuid2);
	}

}

/******* S.D.G. *******/
