/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.box.commands;

import java.time.LocalDateTime;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.box.data.IScoreCardData;
import com.anfelisa.box.models.IBoxModel;
import com.anfelisa.box.models.IReinforceCardModel;
import com.anfelisa.box.models.IScheduledCardModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class ScoreCardCommand extends AbstractScoreCardCommand {

	static final Logger LOG = LoggerFactory.getLogger(ScoreCardCommand.class);

	public ScoreCardCommand(IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected IScoreCardData executeCommand(IScoreCardData data, PersistenceHandle readonlyHandle) {
		IScheduledCardModel scheduledCard = this.daoProvider.getScheduledCardDao().selectByScheduledCardId(
				readonlyHandle,
				data.getScheduledCardId());
		if (scheduledCard == null) {
			throwIllegalArgumentException("cardDoesNotExist");
		}
		IBoxModel box = daoProvider.getBoxDao().selectByBoxId(readonlyHandle, scheduledCard.getBoxId());
		if (!data.getUserId().equals(box.getUserId())) {
			throwSecurityException();
		}

		Float ef = scheduledCard.getEf();
		Integer interval = scheduledCard.getInterval();
		Integer count = scheduledCard.getCount() + 1;
		Integer n = scheduledCard.getN() + 1;
		Float newFactor = ef;
		Integer quality = data.getScoredCardQuality();

		if (quality < 3) {
			n = 1;
		} else {
			Float qFactor = (float) (5 - quality);
			newFactor = (ef + (0.1F - qFactor * (0.08F + qFactor * 0.02F)));
			if (newFactor < 1.3) {
				newFactor = 1.3F;
			}
		}

		IReinforceCardModel reinforceCard = daoProvider.getReinforceCardDao().selectByScheduledCardId(readonlyHandle,
				scheduledCard.getScheduledCardId());
		this.addScoreOutcome(data);
		if (quality <= 3 && reinforceCard == null) {
			this.addReinforceOutcome(data);
		}
		Integer newInterval = 1;
		if (n == 2) {
			newInterval = 6;
		} else if (n > 2) {
			newInterval = Math.round(interval * newFactor);
		}
		if (box.getMaxInterval() != null && newInterval > box.getMaxInterval()) {
			newInterval = box.getMaxInterval();
		}
		LocalDateTime newTime = data.getSystemTime().plusDays(newInterval);
		if (box.getMaxCardsPerDay() != null) {
			newTime = data.getSystemTime().plusDays(newInterval);
			Integer cardCount = daoProvider.getScheduledCardDao().selectCardCountOfDay(readonlyHandle, box.getBoxId(),
					newTime.withHour(0).withMinute(0).withSecond(0).withNano(0), newTime.plusDays(1).withHour(0).withMinute(0).withSecond(0).withNano(0));
			while (cardCount >= box.getMaxCardsPerDay()) {
				newInterval += 1;
				newTime = data.getSystemTime().plusDays(newInterval);
				cardCount = daoProvider.getScheduledCardDao().selectCardCountOfDay(readonlyHandle, box.getBoxId(),
						newTime.withHour(0).withMinute(0).withSecond(0).withNano(0), newTime.plusDays(1).withHour(0).withMinute(0).withSecond(0).withNano(0));
			}
		}
		data.setNextScheduledCardScheduledCardId(data.getUuid());
		data.setNextScheduledCardEf(newFactor);
		data.setNextScheduledCardInterval(newInterval);
		data.setNextScheduledCardCount(count);
		data.setNextScheduledCardN(n);
		data.setNextScheduledCardScheduledDate(newTime);
		data.setNextScheduledCardLastQuality(quality);
		data.setNextScheduledCardCreatedDate(data.getSystemTime());

		data.setCardId(scheduledCard.getCardId());
		data.setBoxId(scheduledCard.getBoxId());

		data.setScoredCardScoredDate(data.getSystemTime());

		data.setReinforceCardId(data.getUuid());
		data.setReinforceCardCreatedDate(data.getSystemTime());
		return data;
	}

}




/******* S.D.G. *******/



