/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.box.commands;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.box.models.BoxModel;
import com.anfelisa.box.models.ReinforceCardModel;
import com.anfelisa.box.models.ScoreReinforceCardModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.Data;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class ScoreReinforceCardCommand extends AbstractScoreReinforceCardCommand {

	static final Logger LOG = LoggerFactory.getLogger(ScoreReinforceCardCommand.class);

	public ScoreReinforceCardCommand(IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected Data<ScoreReinforceCardModel> executeCommand(Data<ScoreReinforceCardModel> data, PersistenceHandle readonlyHandle) {
		ReinforceCardModel reinforceCard = this.daoProvider.getReinforceCardDao().selectByReinforceCardId(readonlyHandle, data.getModel().getReinforceCardId());
		if (reinforceCard == null) {
			throwIllegalArgumentException("cardDoesNotExist");
		}
		BoxModel box = this.daoProvider.getBoxDao().selectByBoxId(readonlyHandle, reinforceCard.getBoxId());
		if (!box.getUserId().equals(data.getModel().getUserId())) {
			throwSecurityException();
		}
		if (data.getModel().getKeep()) {
			this.addKeepOutcome(data);
			data.getModel().setChangeDate(data.getSystemTime());
		} else {
			this.addRemoveOutcome(data);
		}
		return data;
	}

}




/******* S.D.G. *******/



