/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




package com.anfelisa.box.commands;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.box.data.IScoreReinforceCardData;
import com.anfelisa.box.models.IBoxModel;
import com.anfelisa.box.models.IReinforceCardModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class ScoreReinforceCardCommand extends AbstractScoreReinforceCardCommand {

	static final Logger LOG = LoggerFactory.getLogger(ScoreReinforceCardCommand.class);

	public ScoreReinforceCardCommand(IDaoProvider daoProvider, ViewProvider viewProvider, 
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected IScoreReinforceCardData executeCommand(IScoreReinforceCardData data, PersistenceHandle readonlyHandle) {
		IReinforceCardModel reinforceCard = this.daoProvider.getReinforceCardDao().selectByReinforceCardId(readonlyHandle, data.getReinforceCardId());
		if (reinforceCard == null) {
			throwIllegalArgumentException("cardDoesNotExist");
		}
		IBoxModel box = this.daoProvider.getBoxDao().selectByBoxId(readonlyHandle, reinforceCard.getBoxId());
		if (!box.getUserId().equals(data.getUserId())) {
			throwSecurityException();
		}
		if (data.getKeep()) {
			this.addKeepOutcome(data);
			data.setChangeDate(data.getSystemTime());
		} else {
			this.addRemoveOutcome(data);
		}
		return data;
	}

}




/******* S.D.G. *******/



