/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/

package com.anfelisa.box.commands;

import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.box.data.ISortCardsOutData;
import com.anfelisa.box.models.IBoxModel;
import com.anfelisa.box.models.IReinforceCardModel;
import com.anfelisa.box.models.IScheduledCardModel;
import com.anfelisa.card.models.ICardModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class SortCardsOutCommand extends AbstractSortCardsOutCommand {

	static final Logger LOG = LoggerFactory.getLogger(SortCardsOutCommand.class);

	public SortCardsOutCommand(IDaoProvider daoProvider, ViewProvider viewProvider,
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected ISortCardsOutData executeCommand(ISortCardsOutData data, PersistenceHandle readonlyHandle) {
		if (data.getCardIds() == null || data.getCardIds().isEmpty()) {
			this.addNullOrEmptyOutcome(data);
		} else {
			data.setSortedOutScheduledCardIds(new ArrayList<String>());
			data.setSortedOutReinforceCardIds(new ArrayList<String>());
			IBoxModel box = daoProvider.getBoxDao().selectByBoxId(readonlyHandle, data.getBoxId());
			if (box == null) {
				throwIllegalArgumentException("boxDoesNotExist");
			}
			if (!box.getUserId().equals(data.getUserId())) {
				throwSecurityException();
			}
			for (String cardId : data.getCardIds()) {
				ICardModel card = daoProvider.getCardDao().selectByCardId(readonlyHandle, cardId);
				if (card == null) {
					throwIllegalArgumentException("cardDoesNotExist");
				}
				IScheduledCardModel scheduledCard = daoProvider.getScheduledCardDao()
						.selectUnscoredByCardIdAndBoxId(readonlyHandle, cardId, box.getBoxId());
				if (scheduledCard != null) {
					data.getSortedOutScheduledCardIds().add(scheduledCard.getScheduledCardId());
					List<IReinforceCardModel> allOfCard = daoProvider.getReinforceCardDao()
							.selectAllOfCard(readonlyHandle, cardId);
					for (IReinforceCardModel reinforceCard : allOfCard) {
						data.getSortedOutReinforceCardIds().add(reinforceCard.getReinforceCardId());
					}
				}
			}
			this.addOkOutcome(data);
		}
		return data;
	}
}

/******* S.D.G. *******/
