/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/

package com.anfelisa.box.commands;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anfelisa.box.data.IBoxUpdateData;
import com.anfelisa.box.models.IBoxModel;
import com.anfelisa.box.utils.LanguageValidator;
import com.anfelisa.category.models.IUserAccessToCategoryModel;

import de.acegen.CustomAppConfiguration;
import de.acegen.IDaoProvider;
import de.acegen.PersistenceHandle;
import de.acegen.ViewProvider;

public class UpdateBoxCommand extends AbstractUpdateBoxCommand {

	static final Logger LOG = LoggerFactory.getLogger(UpdateBoxCommand.class);

	public UpdateBoxCommand(IDaoProvider daoProvider, ViewProvider viewProvider,
			CustomAppConfiguration appConfiguration) {
		super(daoProvider, viewProvider, appConfiguration);
	}

	@Override
	protected IBoxUpdateData executeCommand(IBoxUpdateData data, PersistenceHandle readonlyHandle) {
		IBoxModel box = daoProvider.getBoxDao().selectByBoxId(readonlyHandle, data.getBoxId());
		if (!box.getUserId().equals(data.getUserId())) {
			throwSecurityException();
		}
		IUserAccessToCategoryModel access = daoProvider.getUserAccessToCategoryDao()
				.selectByCategoryIdAndUserId(readonlyHandle, box.getCategoryId(), data.getUserId());
		if (access == null) {
			throwSecurityException();
		}
		if (access.getEditable()) {
			this.addCanEditCategoryOutcome(data);
		}

		if (data.getMaxCardsPerDay() == 0) {
			throwIllegalArgumentException("maxCardsPerDayMustNotBeZero");
		}

		if (data.getDictionaryLookup() != null && data.getDictionaryLookup()) {
			if (!LanguageValidator.isLanguageValid(data.getGivenLanguage())) {
				throwIllegalArgumentException("givenLanguageIsInvalid");
			}
			if (!LanguageValidator.isLanguageValid(data.getWantedLanguage())) {
				throwIllegalArgumentException("wantedLanguageIsInvalid");
			}
		} else {
			data.setGivenLanguage(null);
			data.setWantedLanguage(null);
		}
		this.addOkOutcome(data);
		return data;
	}

}

/******* S.D.G. *******/
