/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.user.deleteuser.scenarios;


public class DeleteDoesNotDeleteUserWhenBoxIsSharedScenario extends AbstractDeleteDoesNotDeleteUserWhenBoxIsSharedScenario {

	

}




/******* S.D.G. *******/



