/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.user.deleteuser.scenarios;

import com.anfelisa.user.data.DeleteUserResponse;

@SuppressWarnings("unused")
public class DoesNotDeleteSharedCategoriesAndCardsWhenThereIsAnotherUserWithWriteAccessScenario extends AbstractDoesNotDeleteSharedCategoriesAndCardsWhenThereIsAnotherUserWithWriteAccessScenario {

	

}




/******* S.D.G. *******/



