/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




package com.anfelisa.user.getuserinfo.scenarios;

import com.anfelisa.user.data.GetUserInfoResponse;

@SuppressWarnings("unused")
public class GetUserInfoScenario extends AbstractGetUserInfoScenario {

	

}




/******* S.D.G. *******/



