/********************************************************************************
 * generated by de.acegen 1.0.0
 ********************************************************************************/




package com.anfelisa.card.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CardListData extends AbstractCardListData implements ICardListData {
	
	public CardListData(
		@JsonProperty("userId") String userId, 
		@JsonProperty("cardList") java.util.List<com.anfelisa.card.models.ICardWithInfoModel> cardList, 
		@JsonProperty("categoryId") String categoryId, 
		@JsonProperty("filterNonScheduled") Boolean filterNonScheduled, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			userId,
			cardList,
			categoryId,
			filterNonScheduled,
			uuid
		);
	}

	public CardListData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.card.models.ICardListModel generateTestData() {
		java.util.Random random = new java.util.Random();
		int n;
		com.anfelisa.card.models.ICardListModel testData = new com.anfelisa.card.models.CardListModel();
		testData.setUserId(randomString(random));
		java.util.List<com.anfelisa.card.models.ICardWithInfoModel> cardListList = new java.util.ArrayList<com.anfelisa.card.models.ICardWithInfoModel>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			cardListList.add(com.anfelisa.card.data.CardWithInfoData.generateTestData());
		}
		testData.setCardList(cardListList);
		testData.setCategoryId(randomString(random));
		testData.setFilterNonScheduled(random.nextBoolean());
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



