/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.card.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CardUpdatePriorityData extends AbstractCardUpdatePriorityData implements ICardUpdatePriorityData {
	
	public CardUpdatePriorityData(
		@JsonProperty("cardId") String cardId, 
		@JsonProperty("priority") Integer priority, 
		@JsonProperty("userId") String userId, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			cardId,
			priority,
			userId,
			uuid
		);
	}

	public CardUpdatePriorityData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.card.models.ICardUpdatePriorityModel generateTestData() {
		java.util.Random random = new java.util.Random();
		com.anfelisa.card.models.ICardUpdatePriorityModel testData = new com.anfelisa.card.models.CardUpdatePriorityModel();
		testData.setCardId(randomString(random));
		testData.setPriority(random.nextInt(50));
		testData.setUserId(randomString(random));
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



