/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.card.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CardSearchData extends AbstractCardSearchData implements ICardSearchData {
	
	public CardSearchData(
		@JsonProperty("userId") String userId, 
		@JsonProperty("given") String given, 
		@JsonProperty("wanted") String wanted, 
		@JsonProperty("categoryId") String categoryId, 
		@JsonProperty("cardList") java.util.List<com.anfelisa.card.models.ICardWithCategoryNameModel> cardList, 
		@JsonProperty("naturalInputOrder") Boolean naturalInputOrder, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			userId,
			given,
			wanted,
			categoryId,
			cardList,
			naturalInputOrder,
			uuid
		);
	}

	public CardSearchData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.card.models.ICardSearchModel generateTestData() {
		java.util.Random random = new java.util.Random();
		int n;
		com.anfelisa.card.models.ICardSearchModel testData = new com.anfelisa.card.models.CardSearchModel();
		testData.setUserId(randomString(random));
		testData.setGiven(randomString(random));
		testData.setWanted(randomString(random));
		testData.setCategoryId(randomString(random));
		java.util.List<com.anfelisa.card.models.ICardWithCategoryNameModel> cardListList = new java.util.ArrayList<com.anfelisa.card.models.ICardWithCategoryNameModel>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			cardListList.add(com.anfelisa.card.data.CardWithCategoryNameData.generateTestData());
		}
		testData.setCardList(cardListList);
		testData.setNaturalInputOrder(new Boolean(random.nextBoolean()));
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



