/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.card.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ChangeCardOrderListData extends AbstractChangeCardOrderListData implements IChangeCardOrderListData {
	
	public ChangeCardOrderListData(
		@JsonProperty("cardIdList") java.util.List<String> cardIdList, 
		@JsonProperty("cardId") String cardId, 
		@JsonProperty("userId") String userId, 
		@JsonProperty("updatedIndices") java.util.List<com.anfelisa.card.models.ICardModel> updatedIndices, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			cardIdList,
			cardId,
			userId,
			updatedIndices,
			uuid
		);
	}

	public ChangeCardOrderListData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.card.models.IChangeCardOrderListModel generateTestData() {
		java.util.Random random = new java.util.Random();
		int n;
		com.anfelisa.card.models.IChangeCardOrderListModel testData = new com.anfelisa.card.models.ChangeCardOrderListModel();
		java.util.List<String> cardIdListList = new java.util.ArrayList<String>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			cardIdListList.add(randomString(random));
		}
		testData.setCardIdList(cardIdListList);
		testData.setCardId(randomString(random));
		testData.setUserId(randomString(random));
		java.util.List<com.anfelisa.card.models.ICardModel> updatedIndicesList = new java.util.ArrayList<com.anfelisa.card.models.ICardModel>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			updatedIndicesList.add(com.anfelisa.card.data.CardData.generateTestData());
		}
		testData.setUpdatedIndices(updatedIndicesList);
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



