/********************************************************************************
 * generated by de.acegen 0.9.10
 ********************************************************************************/




package com.anfelisa.card.data;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CsvUploadData extends AbstractCsvUploadData implements ICsvUploadData {
	
	public CsvUploadData(
		@JsonProperty("userId") String userId, 
		@JsonProperty("categoryId") String categoryId, 
		@JsonProperty("previewCsv") java.util.List<com.anfelisa.card.models.ISimpleCardModel> previewCsv, 
		@JsonProperty("cards") java.util.List<com.anfelisa.card.models.ICardModel> cards, 
		@JsonProperty("uuid") String uuid
	) {
		super(
			userId,
			categoryId,
			previewCsv,
			cards,
			uuid
		);
	}

	public CsvUploadData( String uuid ) {
		super(uuid);
	}

	public void migrateLegacyData(String json) {
	}

	public static com.anfelisa.card.models.ICsvUploadModel generateTestData() {
		java.util.Random random = new java.util.Random();
		int n;
		com.anfelisa.card.models.ICsvUploadModel testData = new com.anfelisa.card.models.CsvUploadModel();
		testData.setUserId(randomString(random));
		testData.setCategoryId(randomString(random));
		java.util.List<com.anfelisa.card.models.ISimpleCardModel> previewCsvList = new java.util.ArrayList<com.anfelisa.card.models.ISimpleCardModel>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			previewCsvList.add(com.anfelisa.card.data.SimpleCardData.generateTestData());
		}
		testData.setPreviewCsv(previewCsvList);
		java.util.List<com.anfelisa.card.models.ICardModel> cardsList = new java.util.ArrayList<com.anfelisa.card.models.ICardModel>();
		n = random.nextInt(20) + 1;
		for ( int i = 0; i < n; i++ ) {
			cardsList.add(com.anfelisa.card.data.CardData.generateTestData());
		}
		testData.setCards(cardsList);
		return testData;
	}
	
	private static String randomString(java.util.Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int n = random.nextInt(20) + 5;
		StringBuilder sb = new StringBuilder(n);
		for (int i = 0; i < n; i++) {
			int index = random.nextInt(chars.length());
			sb.append(chars.charAt(index));
		}
		String string  = sb.toString(); 
		return string.substring(0,1).toUpperCase() + string.substring(1).toLowerCase();
	}
	
}



/******* S.D.G. *******/



