/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.searchusername.scenarios;

import com.anfelisa.category.data.SearchUsernameForInvitationResponse;

@SuppressWarnings("unused")
public class SearchUsernameNoEditingAccessToCategoryScenario extends AbstractSearchUsernameNoEditingAccessToCategoryScenario {

	

}




/******* S.D.G. *******/



