/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.searchusername.scenarios;

@SuppressWarnings("unused")
public class SearchUsernameNarrowScenario extends AbstractSearchUsernameNarrowScenario {

	@Override
	protected void responseUsernamesShouldStartWithAnnette(com.anfelisa.category.data.SearchUsernameForInvitationResponse response) {
		for (String username : response.getUsernames()) {
			assertTrue(username.startsWith("Annette"));
		}
		LOG.info("THEN: responseUsernamesShouldStartWithAnnette passed");
	}
	@Override
	protected void responseShouldBeLimitedToTen(com.anfelisa.category.data.SearchUsernameForInvitationResponse response) {
		assertTrue(response.getUsernames().size() <= 10);
		LOG.info("THEN: responseShouldBeLimitedToTen passed");
	}
	

}




/******* S.D.G. *******/



