/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.searchusername.scenarios;

@SuppressWarnings("unused")
public class SearchUsernameNoAccessToCategoryScenario extends AbstractSearchUsernameNoAccessToCategoryScenario {

	

}




/******* S.D.G. *******/



