/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.searchusername.scenarios;

@SuppressWarnings("unused")
public class SearchUsernameExactScenario extends AbstractSearchUsernameExactScenario {

	

}




/******* S.D.G. *******/



