/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.inviteusertocategory.scenarios;

@SuppressWarnings("unused")
public class InviteUserToCategoryNoEditingAccessToCategoryScenario extends AbstractInviteUserToCategoryNoEditingAccessToCategoryScenario {

	

}




/******* S.D.G. *******/



