/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.category.inviteusertocategory.scenarios;


public class InviteTwoUsersToCategoryScenario extends AbstractInviteTwoUsersToCategoryScenario {

	

}




/******* S.D.G. *******/



