/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.category.inviteusertocategory.scenarios;


public class InviteUserChangeEditableFalseScenario extends AbstractInviteUserChangeEditableFalseScenario {

	

}




/******* S.D.G. *******/



