/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.category.inviteusertocategory.scenarios;


public class InviteUserToCategoryUseMaxCardsPerDayAndMaxIntervalOfOriginalBoxScenario extends AbstractInviteUserToCategoryUseMaxCardsPerDayAndMaxIntervalOfOriginalBoxScenario {

	

}




/******* S.D.G. *******/



