/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.category.inviteusertocategory.scenarios;

import com.anfelisa.category.data.InviteUserToCategoryResponse;

@SuppressWarnings("unused")
public class InviteUserToCategoryEditableScenario extends AbstractInviteUserToCategoryEditableScenario {

	

}




/******* S.D.G. *******/



