/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




package com.anfelisa.category.inviteusertocategory.scenarios;


public class InviteUserChangeEditableTrueScenario extends AbstractInviteUserChangeEditableTrueScenario {

	

}




/******* S.D.G. *******/



