/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




package com.anfelisa.category.inviteusertocategory.scenarios;

import com.anfelisa.category.data.InviteUserToCategoryResponse;

@SuppressWarnings("unused")
public class InviteUserToCategoryNoAccessToCategoryScenario extends AbstractInviteUserToCategoryNoAccessToCategoryScenario {

	

}




/******* S.D.G. *******/



